
-- ============================================
-- TABLA DE CONTENIDOS DE LIBROS
-- Referencias a páginas específicas de cada libro
-- ============================================

DROP TABLE IF EXISTS public.book_contents CASCADE;

CREATE TABLE public.book_contents (
  id BIGSERIAL PRIMARY KEY,
  book_slug TEXT NOT NULL REFERENCES public.books(slug) ON DELETE CASCADE,
  content_type TEXT NOT NULL, -- 'chapter', 'class', 'race', 'feat', 'skill', 'spell', 'equipment', 'monster', 'magic_item', 'other'
  title TEXT NOT NULL,
  page_number INTEGER NOT NULL,
  source_page INTEGER, -- Página del PDF donde se encuentra el índice

  -- Enlaces opcionales a entradas existentes en otras tablas
  class_slug TEXT REFERENCES public.classes(slug),
  race_slug TEXT REFERENCES public.races(slug),
  feat_slug TEXT REFERENCES public.feats(slug),
  skill_slug TEXT REFERENCES public.skills(slug),
  spell_slug TEXT REFERENCES public.spells(slug),

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Índice único por libro, tipo y título
  UNIQUE(book_slug, content_type, title)
);

-- Índices para consultas rápidas
CREATE INDEX idx_book_contents_book ON public.book_contents(book_slug);
CREATE INDEX idx_book_contents_type ON public.book_contents(content_type);
CREATE INDEX idx_book_contents_page ON public.book_contents(page_number);
CREATE INDEX idx_book_contents_title ON public.book_contents USING gin(to_tsvector('english', title));

-- Comentarios
COMMENT ON TABLE public.book_contents IS 'Índice de contenidos de todos los libros D&D 3.5 extraído de los PDFs';
COMMENT ON COLUMN public.book_contents.content_type IS 'Tipo de contenido: chapter, class, race, feat, skill, spell, equipment, monster, magic_item, other';
COMMENT ON COLUMN public.book_contents.page_number IS 'Número de página donde comienza el contenido en el PDF del libro';
COMMENT ON COLUMN public.book_contents.source_page IS 'Número de página del PDF donde se encontró esta entrada del índice';


-- Contenidos de Player's Handbook (123 entradas)
INSERT INTO public.book_contents (book_slug, content_type, title, page_number, source_page)
VALUES
  ('player-handbook', 'other', 'Goods and Services........................................126 Unarmed Damage', 41, 4),
  ('player-handbook', 'class', 'Table 3–12: The Paladin', 43, 4),
  ('player-handbook', 'class', 'Table 3–13: The Ranger', 46, 4),
  ('player-handbook', 'chapter', 'Chapter 8: Combat', 133, 4),
  ('player-handbook', 'other', 'Introduction', 4, 4),
  ('player-handbook', 'class', 'The Battle Grid................................................133 Table 3–14: Ranger Favored Enemies', 47, 4),
  ('player-handbook', 'class', 'How Combat Works.....................................133 Table 3–15: The Rogue', 49, 4),
  ('player-handbook', 'other', 'Character Creation Summary', 6, 4),
  ('player-handbook', 'class', 'Combat Statistics............................................133 Table 3–16: The Sorcerer', 52, 4),
  ('player-handbook', 'class', 'Combat Basics.................................................135 Table 3–17: Sorcerer Spells Known', 54, 4),
  ('player-handbook', 'chapter', 'Chapter 1: Abilities', 7, 4),
  ('player-handbook', 'class', 'Initiative...........................................................136 Table 3–18: The Wizard', 55, 4),
  ('player-handbook', 'other', 'Ability Scores', 7, 4),
  ('player-handbook', 'skill', 'Attacks of Opportunity................................137 Table 4–1: Skill Points per Level', 62, 4),
  ('player-handbook', 'other', 'The Abilities', 8, 4),
  ('player-handbook', 'skill', 'Actions in Combat.........................................138 Table 4–2: Skills', 63, 4),
  ('player-handbook', 'other', 'Changing Ability Scores', 10, 4),
  ('player-handbook', 'other', 'Injury and Death............................................145 Table 4–3: Difficulty Class Examples', 64, 4),
  ('player-handbook', 'other', 'Movement, Position, Table 4–4: Example Opposed Checks', 64, 4),
  ('player-handbook', 'chapter', 'Chapter 2: Races', 11, 4),
  ('player-handbook', 'skill', 'And Distance..............................................146 Table 4–5: Skill Synergies', 66, 4),
  ('player-handbook', 'other', 'Choosing a Race', 11, 4),
  ('player-handbook', 'other', 'Combat Modifiers..........................................150 Table 4–6: Example Ability Checks', 66, 4),
  ('player-handbook', 'other', 'Racial Characteristics', 11, 4),
  ('player-handbook', 'feat', 'Special Attacks................................................154 Table 5–1: Feats', 90, 4),
  ('player-handbook', 'other', 'Humans', 12, 4),
  ('player-handbook', 'other', 'Dwarves', 14, 4),
  ('player-handbook', 'other', 'Class Alignments', 104, 4),
  ('player-handbook', 'other', 'Elves', 15, 4),
  ('player-handbook', 'chapter', 'Chapter 9: Adventuring................................161 Table 6–2: Deities by Race', 106, 4),
  ('player-handbook', 'other', 'Gnomes', 16, 4),
  ('player-handbook', 'other', 'Carrying Capacity..........................................161 Table 6–3: Deities by Class', 106, 4),
  ('player-handbook', 'other', 'Half-Elves', 18, 4),
  ('player-handbook', 'other', 'Movement........................................................162 Table 6–4: Random Starting Ages', 109, 4),
  ('player-handbook', 'other', 'Half-Orcs', 18, 4),
  ('player-handbook', 'other', 'Exploration......................................................164 Table 6–5: Aging Effects', 109, 4),
  ('player-handbook', 'other', 'Halflings', 19, 4),
  ('player-handbook', 'other', 'Other Rewards................................................168 and Weight', 109, 4),
  ('player-handbook', 'chapter', 'Chapter 3: Classes', 21, 4),
  ('player-handbook', 'other', 'Table 7–1: Random Starting Gold', 111, 4),
  ('player-handbook', 'other', 'The Classes', 21, 4),
  ('player-handbook', 'other', 'Magic.............................................169 Table 7–2: Coins', 112, 4),
  ('player-handbook', 'other', 'Class and Level Bonuses', 21, 4),
  ('player-handbook', 'spell', 'Casting Spells..................................................169 Table 7–3: Trade Goods', 112, 4),
  ('player-handbook', 'other', 'Level-Dependent Benefits', 22, 4),
  ('player-handbook', 'spell', 'Spell Descriptions', 172, 4),
  ('player-handbook', 'other', 'Class Descriptions', 23, 4),
  ('player-handbook', 'equipment', 'Weapon Damage', 114, 4),
  ('player-handbook', 'spell', 'Arcane Spells', 177, 4),
  ('player-handbook', 'class', 'Barbarian', 24, 4),
  ('player-handbook', 'equipment', 'Table 7–5: Weapons', 116, 4),
  ('player-handbook', 'spell', 'Divine Spells', 179, 4),
  ('player-handbook', 'class', 'Bard', 26, 4),
  ('player-handbook', 'equipment', 'Special Abilities..............................................180 Table 7–6: Armor and Shields', 123, 4),
  ('player-handbook', 'class', 'Cleric', 30, 4),
  ('player-handbook', 'equipment', 'Table 7–7: Donning Armor', 123, 4),
  ('player-handbook', 'class', 'Druid', 33, 4),
  ('player-handbook', 'chapter', 'Chapter 11: Spells.............................................181 Table 7–8: Goods and Services', 128, 4),
  ('player-handbook', 'class', 'Fighter', 37, 4),
  ('player-handbook', 'class', 'Bard Spells........................................................181 Table 8–1: Size Modifiers', 134, 4),
  ('player-handbook', 'class', 'Monk', 39, 4),
  ('player-handbook', 'class', 'Cleric Spells.....................................................183 Table 8–2: Actions in Combat', 141, 4),
  ('player-handbook', 'class', 'Paladin', 42, 4),
  ('player-handbook', 'class', 'Cleric Domains...............................................185 Table 8–3: Tactical Speed', 147, 4),
  ('player-handbook', 'class', 'Ranger', 46, 4),
  ('player-handbook', 'class', 'Druid Spells.....................................................189 Table 8–4: Creature Size and Scale', 149, 4),
  ('player-handbook', 'class', 'Rogue', 49, 4),
  ('player-handbook', 'class', 'Paladin Spells..................................................191 Table 8–5: Attack Roll Modifiers', 151, 4),
  ('player-handbook', 'class', 'Sorcerer', 51, 4),
  ('player-handbook', 'equipment', 'Table 8–6: Armor Class Modifiers', 151, 4),
  ('player-handbook', 'class', 'Ranger Spells', 191, 4),
  ('player-handbook', 'class', 'Wizard', 55, 4),
  ('player-handbook', 'other', 'Table 8–7: Special Attacks', 154, 4),
  ('player-handbook', 'class', 'Sorcerer/Wizard Spells', 192, 4),
  ('player-handbook', 'other', 'Experience and Levels', 58, 4),
  ('player-handbook', 'spell', 'Spells', 196, 4),
  ('player-handbook', 'other', 'Multiclass Characters', 59, 4),
  ('player-handbook', 'other', 'Shield Hardness and Hit Points', 158, 4),
  ('player-handbook', 'other', 'Table 8–9: Turning Undead', 159, 4),
  ('player-handbook', 'chapter', 'Chapter 4: Skills', 61, 4),
  ('player-handbook', 'other', 'and Glossary', 304, 4),
  ('player-handbook', 'skill', 'Skill Summary', 61, 4),
  ('player-handbook', 'other', 'Fighting Penalties', 160, 4),
  ('player-handbook', 'skill', 'Acquiring Skill Ranks', 61, 4),
  ('player-handbook', 'other', 'Index......................................................................315 Table 9–1: Carrying Capacity', 162, 4),
  ('player-handbook', 'skill', 'Using Skills', 62, 4),
  ('player-handbook', 'other', 'Table 9–2: Carrying Loads', 162, 4),
  ('player-handbook', 'skill', 'Skill Descriptions', 66, 4),
  ('player-handbook', 'other', 'Sheet', 318, 4),
  ('player-handbook', 'other', 'Character Table 9–3: Movement and Distance', 162, 4),
  ('player-handbook', 'other', 'Table 9–4: Hampered Movement', 163, 4),
  ('player-handbook', 'chapter', 'Chapter 5: Feats', 87, 4),
  ('player-handbook', 'feat', 'Acquiring Feats', 87, 4),
  ('player-handbook', 'other', 'Movement', 164, 4),
  ('player-handbook', 'other', 'Prerequisites', 87, 4),
  ('player-handbook', 'spell', 'and Bonus Spells', 8, 4),
  ('player-handbook', 'other', 'Table 9–6: Mounts and Vehicles', 164, 4),
  ('player-handbook', 'feat', 'Types of Feats', 87, 4),
  ('player-handbook', 'other', 'Table 2–1: Racial Ability Adjustments', 12, 4),
  ('player-handbook', 'feat', 'Feat Descriptions', 89, 4),
  ('player-handbook', 'other', 'and Illumination', 165, 4),
  ('player-handbook', 'other', 'Base Attack Bonuses', 22, 4),
  ('player-handbook', 'chapter', 'Chapter 6: Description', 103, 4),
  ('player-handbook', 'other', 'Alignment', 103, 4),
  ('player-handbook', 'other', 'Dependent Benefits', 22, 4),
  ('player-handbook', 'other', 'Religion', 106, 4),
  ('player-handbook', 'class', 'Table 3–3: The Barbarian', 25, 4),
  ('player-handbook', 'other', 'and Hit Points', 166, 4),
  ('player-handbook', 'other', 'Vital Statistics', 109, 4),
  ('player-handbook', 'class', 'Table 3–4: The Bard', 27, 4),
  ('player-handbook', 'class', 'Table 3–5: Bard Spells Known', 28, 4),
  ('player-handbook', 'other', 'of Objects', 166, 4),
  ('player-handbook', 'other', 'and Background', 110, 4),
  ('player-handbook', 'class', 'Table 3–6: The Cleric', 31, 4),
  ('player-handbook', 'other', 'Customizing Your Character', 110, 4),
  ('player-handbook', 'other', 'Table 3–7: Deities', 32, 4),
  ('player-handbook', 'class', 'Table 3–8: The Druid', 35, 4),
  ('player-handbook', 'chapter', 'Chapter 7: Equipment', 111, 4),
  ('player-handbook', 'class', 'Table 3–9: The Fighter', 39, 4),
  ('player-handbook', 'other', 'Equipping a Character.................................111 Burst Items', 166, 4),
  ('player-handbook', 'class', 'Table 3–10: The Monk', 40, 4),
  ('player-handbook', 'other', 'Wealth and Money', 112, 4),
  ('player-handbook', 'equipment', 'Weapons...........................................................112 Magical Attacks', 177, 4)
ON CONFLICT (book_slug, content_type, title) DO UPDATE
  SET page_number = EXCLUDED.page_number,
      source_page = EXCLUDED.source_page,
      updated_at = NOW();


-- Contenidos de Dungeon Master's Guide (67 entradas)
INSERT INTO public.book_contents (book_slug, content_type, title, page_number, source_page)
VALUES
  ('dungeon-masters-guide', 'feat', 'Miscellaneous Features. . . . . . . . . 63 Class/Race Restrictions', 171, 4),
  ('dungeon-masters-guide', 'other', 'Cave-Ins and Collapses. . . . . . . . . 66 New Races', 171, 4),
  ('dungeon-masters-guide', 'monster', 'Illumination. . . . . . . . . . . . . . . . . . . 67 Monsters as Races', 172, 4),
  ('dungeon-masters-guide', 'other', 'Introduction. . . . . . . . . . . . . . . . . . . . . . . . 4 Traps. . . . . . . . . . . . . . . . . . . . . . . . . . . . . 67 Classes', 174, 4),
  ('dungeon-masters-guide', 'other', 'Elements of a Trap . . . . . . . . . . . . . 68 Modifying Character Classes', 174, 4),
  ('dungeon-masters-guide', 'other', 'Sample Traps. . . . . . . . . . . . . . . . . . 70 Creating New Classes', 175, 4),
  ('dungeon-masters-guide', 'chapter', 'Chapter 1: Running the Game', 5, 4),
  ('dungeon-masters-guide', 'other', 'What Is a DM?. . . . . . . . . . . . . . . . . . . . . 5 Designing a Trap. . . . . . . . . . . . . . . 74 Prestige Classes', 176, 4),
  ('dungeon-masters-guide', 'other', 'Style of Play . . . . . . . . . . . . . . . . . . . . . . . 7 Dungeon Ecology. . . . . . . . . . . . . . . . . 76 Arcane Archer', 176, 4),
  ('dungeon-masters-guide', 'other', 'Example of Play. . . . . . . . . . . . . . . . . . . . 8 Dungeon Animals. . . . . . . . . . . . . . 76 Arcane Trickster', 177, 4),
  ('dungeon-masters-guide', 'monster', 'Running a Game Session . . . . . . . . . . 10 Wandering Monsters. . . . . . . . . . . 77 Archmage', 178, 4),
  ('dungeon-masters-guide', 'other', 'Random Dungeons. . . . . . . . . . . . . . . . 77 Assassin', 180, 4),
  ('dungeon-masters-guide', 'other', 'More Movement Rules. . . . . . . . . . . . 19 The Map and the Key. . . . . . . . . . . 77 Dragon Disciple', 183, 4),
  ('dungeon-masters-guide', 'other', 'Movement and the Grid. . . . . . . . 19 Random Dungeon Encounters. . 78 Duelist', 185, 4),
  ('dungeon-masters-guide', 'other', 'Moving in Three Dimensions. . . 20 A Sample Adventure . . . . . . . . . . . . . . 78 Dwarven Defender', 186, 4),
  ('dungeon-masters-guide', 'other', 'Evasion and Pursuit. . . . . . . . . . . . 20 Statistics Blocks. . . . . . . . . . . . . . . . . . . 85 Eldritch Knight', 187, 4),
  ('dungeon-masters-guide', 'other', 'Moving around in Squares. . . . . . 20 Wilderness Adventures. . . . . . . . . . . . 86 Hierophant', 188, 4),
  ('dungeon-masters-guide', 'other', 'Bonus Types. . . . . . . . . . . . . . . . . . . . . . 21 Getting Lost. . . . . . . . . . . . . . . . . . . 86 Horizon Walker', 189, 4),
  ('dungeon-masters-guide', 'other', 'Combat . . . . . . . . . . . . . . . . . . . . . . . . . . 21 Forest Terrain. . . . . . . . . . . . . . . . . . 87 Loremaster', 190, 4),
  ('dungeon-masters-guide', 'other', 'Line of Sight . . . . . . . . . . . . . . . . . . 21 Marsh Terrain . . . . . . . . . . . . . . . . . 88 Mystic Theurge', 192, 4),
  ('dungeon-masters-guide', 'class', 'Starting an Encounter. . . . . . . . . . 22 Hills Terrain. . . . . . . . . . . . . . . . . . . 89 Red Wizard', 193, 4),
  ('dungeon-masters-guide', 'other', 'New Combatants . . . . . . . . . . . . . . 23 Mountain Terrain. . . . . . . . . . . . . . 89 Shadowdancer', 194, 4),
  ('dungeon-masters-guide', 'other', 'Keeping Things Moving. . . . . . . . 24 Desert Terrain . . . . . . . . . . . . . . . . . 91 Thaumaturgist', 196, 4),
  ('dungeon-masters-guide', 'other', 'Combat Actions. . . . . . . . . . . . . . . . 25 Plains Terrain. . . . . . . . . . . . . . . . . . 91 How PCs Improve', 197, 4),
  ('dungeon-masters-guide', 'feat', 'Attack Rolls. . . . . . . . . . . . . . . . . . . 26 Aquatic Terrain . . . . . . . . . . . . . . . . 92 Learning Skills and Feats', 197, 4),
  ('dungeon-masters-guide', 'spell', 'Damage. . . . . . . . . . . . . . . . . . . . . . . 26 Underwater Combat. . . . . . . . . 93 Learning New Spells', 198, 4),
  ('dungeon-masters-guide', 'equipment', 'Effect of Weapon Size. . . . . . . . . . 28 Weather. . . . . . . . . . . . . . . . . . . . . . . 93 Gaining Class Benefits', 198, 4),
  ('dungeon-masters-guide', 'equipment', 'Splash Weapons . . . . . . . . . . . . . . . 28 Random Wilderness General Downtime', 198, 4),
  ('dungeon-masters-guide', 'spell', 'Area Spells. . . . . . . . . . . . . . . . . . . . 28 Encounters. . . . . . . . . . . . . . . . . . 95 Gaining Fixed Hit Points', 198, 4),
  ('dungeon-masters-guide', 'monster', 'Big and Little Creatures Urban Adventures. . . . . . . . . . . . . . . . . 98 Creating PCs above 1st Level', 199, 4),
  ('dungeon-masters-guide', 'spell', 'in Combat . . . . . . . . . . . . . . . . . . 29 Weapon and Spell Restrictions. . 99 Special Cohorts', 199, 4),
  ('dungeon-masters-guide', 'feat', 'Skill and Ability Checks. . . . . . . . . . . 30 Urban Features. . . . . . . . . . . . . . . . 99 Familiars', 200, 4),
  ('dungeon-masters-guide', 'other', 'Saving Throws. . . . . . . . . . . . . . . . . . . . 33 Urban Encounters. . . . . . . . . . . . 101 Mounts', 204, 4),
  ('dungeon-masters-guide', 'other', 'Adjudicating Magic . . . . . . . . . . . . . . . 34 Animal Companions', 205, 4),
  ('dungeon-masters-guide', 'spell', 'Describing Spell Effects. . . . . . . . 34 Chapter 4: Nonplayer Characters . . 103 Epic Characters', 206, 4),
  ('dungeon-masters-guide', 'other', 'Handling Divinations. . . . . . . . . . 34 Everyone in the World', 103, 4),
  ('dungeon-masters-guide', 'spell', 'Creating New Spells. . . . . . . . . . . . 35 NPC Classes. . . . . . . . . . . . . . . . . . . . . 107 Chapter 7: Magic Items', 211, 4),
  ('dungeon-masters-guide', 'magic_item', 'Rewards. . . . . . . . . . . . . . . . . . . . . . . . . . 36 Adept. . . . . . . . . . . . . . . . . . . . . . . . 107 Handling Magic Items', 212, 4),
  ('dungeon-masters-guide', 'magic_item', 'Experience Awards. . . . . . . . . . . . . 36 Aristocrat. . . . . . . . . . . . . . . . . . . . 108 Magic Item Descriptions', 215, 4),
  ('dungeon-masters-guide', 'equipment', 'Story Awards. . . . . . . . . . . . . . . . . . 40 Commoner. . . . . . . . . . . . . . . . . . . 108 Armor', 216, 4),
  ('dungeon-masters-guide', 'equipment', 'Character Death . . . . . . . . . . . . . . . . . . 41 Expert. . . . . . . . . . . . . . . . . . . . . . . 109 Weapons', 221, 4),
  ('dungeon-masters-guide', 'other', 'Making a New Character. . . . . . . 42 Warrior. . . . . . . . . . . . . . . . . . . . . . 109 Potions and Oils', 229, 4),
  ('dungeon-masters-guide', 'other', 'NPC Statistics. . . . . . . . . . . . . . . . . . . 110 Rings', 229, 4),
  ('dungeon-masters-guide', 'chapter', 'Chapter 3: Adventures . . . . . . . . . . . . . 43 NPC Attitudes. . . . . . . . . . . . . . . . . . . 128 Rods', 233, 4),
  ('dungeon-masters-guide', 'other', 'Motivation . . . . . . . . . . . . . . . . . . . . . . . 43 Fleshing out NPCs. . . . . . . . . . . . . . . 128 Scrolls', 237, 4),
  ('dungeon-masters-guide', 'other', 'Structure. . . . . . . . . . . . . . . . . . . . . . . . . 44 Staffs', 243, 4),
  ('dungeon-masters-guide', 'other', 'Site-Based Adventures. . . . . . . . . . . . . 46 Chapter 5: Campaigns. . . . . . . . . . . . . 129 Wands', 245, 4),
  ('dungeon-masters-guide', 'magic_item', 'Event-Based Adventures. . . . . . . . . . . 47 Establishing a Campaign. . . . . . . . . . 129 Wondrous Items', 246, 4),
  ('dungeon-masters-guide', 'other', 'The End (?). . . . . . . . . . . . . . . . . . . . . . . 48 Maintaining a Campaign . . . . . . . . . 130 Intelligent Items', 268, 4),
  ('dungeon-masters-guide', 'other', 'Encounters. . . . . . . . . . . . . . . . . . . . . . . 48 Characters and the World Cursed Items', 272, 4),
  ('dungeon-masters-guide', 'other', 'Tailored or Status Quo. . . . . . . . . . 48 around Them. . . . . . . . . . . . . . . . . . 131 Artifacts', 277, 4),
  ('dungeon-masters-guide', 'magic_item', 'Challenge Ratings and War and Other Calamities . . . . . . . . 133 Creating Magic Items', 282, 4),
  ('dungeon-masters-guide', 'other', 'Encounter Levels. . . . . . . . . . . . 48 Other Campaign Issues. . . . . . . . . . . 134 Masterwork Items', 283, 4),
  ('dungeon-masters-guide', 'other', 'Difficulty . . . . . . . . . . . . . . . . . . . . . 49 World-Building. . . . . . . . . . . . . . . . . . 135 Special Materials', 283, 4),
  ('dungeon-masters-guide', 'monster', 'Tougher Monsters . . . . . . . . . . . . . 50 Building a Different World', 144, 4),
  ('dungeon-masters-guide', 'other', 'Location . . . . . . . . . . . . . . . . . . . . . . 50 Adventuring on Other Planes', 147, 4),
  ('dungeon-masters-guide', 'chapter', 'Chapter 8: Glossary', 289, 4),
  ('dungeon-masters-guide', 'other', 'Rewards and Behavior. . . . . . . . . . 50 Plane Descriptions. . . . . . . . . . . . . . . 151 Special Abilities', 289, 4),
  ('dungeon-masters-guide', 'other', 'Treasure. . . . . . . . . . . . . . . . . . . . . . . . . . 51 Creating a Cosmology. . . . . . . . . . . . 167 Condition Summary', 300, 4),
  ('dungeon-masters-guide', 'other', 'Bringing Adventures Together. . . . . . 56 The Environment', 302, 4),
  ('dungeon-masters-guide', 'other', 'The Dungeon. . . . . . . . . . . . . . . . . . . . . 57 Ability Scores', 169, 4),
  ('dungeon-masters-guide', 'other', 'Visual Aids', 305, 4),
  ('dungeon-masters-guide', 'other', 'Dungeon Terrain. . . . . . . . . . . . . . . . . . 59 Races', 170, 4),
  ('dungeon-masters-guide', 'other', 'Walls . . . . . . . . . . . . . . . . . . . . . . . . . 59 Subraces. . . . . . . . . . . . . . . . . . . . . 170 Index', 317, 4),
  ('dungeon-masters-guide', 'other', 'Doors. . . . . . . . . . . . . . . . . . . . . . . . . 60 Modifying a Common Race. . . . 171 List of Sidebars', 319, 4),
  ('dungeon-masters-guide', 'other', 'Rooms. . . . . . . . . . . . . . . . . . . . . . . . 62 Changes through Addition List of Numbered Tables', 320, 4),
  ('dungeon-masters-guide', 'other', 'Corridors . . . . . . . . . . . . . . . . . . . . . 63 and Subtraction', 171, 4)
ON CONFLICT (book_slug, content_type, title) DO UPDATE
  SET page_number = EXCLUDED.page_number,
      source_page = EXCLUDED.source_page,
      updated_at = NOW();


-- Contenidos de Monster Manual (121 entradas)
INSERT INTO public.book_contents (book_slug, content_type, title, page_number, source_page)
VALUES
  ('monster-manual', 'monster', 'Introduction . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5 Chapter 4: Improving Monsters', 290, 3),
  ('monster-manual', 'chapter', 'Chapter 1: Monsters A to Z . . . . . . . . . . . . . . . 8 Chapter 5: Making Monsters', 295, 3),
  ('monster-manual', 'chapter', 'Chapter 2: Animals . . . . . . . . . . . . . . . . . . . . 268 Chapter 6: Monster Skills and Feats', 303, 3),
  ('monster-manual', 'chapter', 'Chapter 3: Vermin . . . . . . . . . . . . . . . . . . . . . 284 Chapter 7: Glossary', 305, 3),
  ('monster-manual', 'other', 'Aasimar (planetouched) . . . 209 Bralani (eladrin) . . . . . . . . . . . 93 Drider . . . . . . . . . . . . . . . . . . . . 89 Girallon', 126, 3),
  ('monster-manual', 'race', 'Aboleth . . . . . . . . . . . . . . . . . . . . 8 Brass dragon. . . . . . . . . . . . . . . 79 Drow (elf )', 103, 3),
  ('monster-manual', 'other', 'Aboleth mage. . . . . . . . . . . . . . . 8 Bronze dragon . . . . . . . . . . . . . 80 Dryad . . . . . . . . . . . . . . . . . . . . . 90 Githzerai', 129, 3),
  ('monster-manual', 'race', 'Bugbear . . . . . . . . . . . . . . . . . . . 29 Duergar (dwarf ) . . . . . . . . . . . 92 Glabrezu (demon)', 43, 3),
  ('monster-manual', 'other', 'Abomination (yuan-ti)', 264, 3),
  ('monster-manual', 'other', 'Abyssal greater basilisk . . . . . 24 Bulette . . . . . . . . . . . . . . . . . . . . 30 Dust mephit . . . . . . . . . . . . . . 181 Gnoll', 130, 3),
  ('monster-manual', 'race', 'Achaierai . . . . . . . . . . . . . . . . . . . 9 Cachalot whale . . . . . . . . . . . 283 Dwarf . . . . . . . . . . . . . . . . . . . . . 91 Gnome', 131, 3),
  ('monster-manual', 'other', 'Goblin', 133, 3),
  ('monster-manual', 'other', 'Air elemental . . . . . . . . . . . . . . 95 Camel . . . . . . . . . . . . . . . . . . . 270 Eagle', 272, 3),
  ('monster-manual', 'other', 'Air mephit . . . . . . . . . . . . . . . 181 Carrion crawler . . . . . . . . . . . . 30 Eagle, giant . . . . . . . . . . . . . . . . 93 Gold dragon', 84, 3),
  ('monster-manual', 'other', 'Cat . . . . . . . . . . . . . . . . . . . . . . 270 Earth elemental. . . . . . . . . . . . 98 Golem', 134, 3),
  ('monster-manual', 'other', 'Allip', 10, 3),
  ('monster-manual', 'other', 'Androsphinx . . . . . . . . . . . . . 232 Cauchemar (nightmare) . . . 195 Earth mephit . . . . . . . . . . . . . 182 Gorgon', 137, 3),
  ('monster-manual', 'race', 'Angel . . . . . . . . . . . . . . . . . . . . . 10 Celestial charger (unicorn). 250 Efreeti . . . . . . . . . . . . . . . . . . . 115 Gray elf', 104, 3),
  ('monster-manual', 'monster', 'Animated object . . . . . . . . . . . 13 Celestial creature. . . . . . . . . . . 31 Eladrin. . . . . . . . . . . . . . . . . . . . 93 Gray ooze', 202, 3),
  ('monster-manual', 'other', 'Ankheg . . . . . . . . . . . . . . . . . . . 14 Centaur . . . . . . . . . . . . . . . . . . . 32 Elasmosaurus (dinosaur) . . . . 60 Gray render', 138, 3),
  ('monster-manual', 'other', 'Chain devil (kyton) . . . . . . . . 53 Elder black pudding. . . . . . . 201 Gray slaad', 231, 3),
  ('monster-manual', 'other', 'Annis (hag)', 143, 3),
  ('monster-manual', 'other', 'Ape . . . . . . . . . . . . . . . . . . . . . . 268 Chaos beast. . . . . . . . . . . . . . . . 33 Elemental . . . . . . . . . . . . . . . . . 95 Greater barghest', 23, 3),
  ('monster-manual', 'other', 'Ape, dire . . . . . . . . . . . . . . . . . . 62 Cheetah. . . . . . . . . . . . . . . . . . 271 Elephant . . . . . . . . . . . . . . . . . 272 Green dragon', 74, 3),
  ('monster-manual', 'race', 'Aquatic elf . . . . . . . . . . . . . . . 103 Chimera . . . . . . . . . . . . . . . . . . 34 Elf . . . . . . . . . . . . . . . . . . . . . . . 101 Green hag', 143, 3),
  ('monster-manual', 'other', 'Aranea . . . . . . . . . . . . . . . . . . . . 15 Choker. . . . . . . . . . . . . . . . . . . . 34 Erinyes (devil) . . . . . . . . . . . . . 54 Green slaad', 230, 3),
  ('monster-manual', 'other', 'Chromatic dragons. . . . . . . . . 70 Ethereal filcher . . . . . . . . . . . 104 Grick', 139, 3),
  ('monster-manual', 'other', 'Archon', 16, 3),
  ('monster-manual', 'other', 'Arrowhawk. . . . . . . . . . . . . . . . 19 Chuul. . . . . . . . . . . . . . . . . . . . . 35 Ethereal marauder . . . . . . . . 105 Griffon', 139, 3),
  ('monster-manual', 'other', 'Assassin vine . . . . . . . . . . . . . . 20 Clay golem . . . . . . . . . . . . . . . 134 Ettercap. . . . . . . . . . . . . . . . . . 106 Grig', 235, 3),
  ('monster-manual', 'other', 'Astral deva (angel) . . . . . . . . . 11 Cloaker . . . . . . . . . . . . . . . . . . . 36 Ettin . . . . . . . . . . . . . . . . . . . . . 106 Grimlock', 140, 3),
  ('monster-manual', 'monster', 'Athach . . . . . . . . . . . . . . . . . . . . 21 Cloud giant. . . . . . . . . . . . . . . 120 Fiendish creature . . . . . . . . . 107 Guardian naga', 192, 3),
  ('monster-manual', 'other', 'Cockatrice. . . . . . . . . . . . . . . . . 37 Fire elemental . . . . . . . . . . . . . 98 Guardinal', 141, 3),
  ('monster-manual', 'other', 'Avoral (guardinal)', 141, 3),
  ('monster-manual', 'other', 'Azer . . . . . . . . . . . . . . . . . . . . . . 21 Constrictor snake . . . . . . . . . 279 Fire giant. . . . . . . . . . . . . . . . . 121 Gynosphinx', 233, 3),
  ('monster-manual', 'other', 'Babau (demon) . . . . . . . . . . . . 40 Copper dragon. . . . . . . . . . . . . 82 Fire mephit. . . . . . . . . . . . . . . 182 Hag', 143, 3),
  ('monster-manual', 'other', 'Baboon . . . . . . . . . . . . . . . . . . 268 Couatl . . . . . . . . . . . . . . . . . . . . 37 Flesh golem . . . . . . . . . . . . . . 135 Half-celestial', 144, 3),
  ('monster-manual', 'race', 'Badger . . . . . . . . . . . . . . . . . . . 268 Crocodile . . . . . . . . . . . . . . . . 271 Forest gnome . . . . . . . . . . . . . 132 Half-dragon', 146, 3),
  ('monster-manual', 'race', 'Criosphinx . . . . . . . . . . . . . . . 233 Formian. . . . . . . . . . . . . . . . . . 108 Half-elf', 102, 3),
  ('monster-manual', 'other', 'Badger, dire', 62, 3),
  ('monster-manual', 'other', 'Baleen whale . . . . . . . . . . . . . 282 Cryohydra. . . . . . . . . . . . . . . . 157 Frost giant. . . . . . . . . . . . . . . . 122 Half-fiend', 147, 3),
  ('monster-manual', 'race', 'Balor (demon) . . . . . . . . . . . . . 40 Dark naga . . . . . . . . . . . . . . . . 191 Frost giant jarl . . . . . . . . . . . . 123 Half-orc', 204, 3),
  ('monster-manual', 'other', 'Barbed devil (hamatula) . . . . 51 Darkmantle. . . . . . . . . . . . . . . . 38 Frost worm. . . . . . . . . . . . . . . 111 Halfblood (yuan-ti)', 264, 3),
  ('monster-manual', 'race', 'Barghest . . . . . . . . . . . . . . . . . . 22 Death slaad . . . . . . . . . . . . . . . 231 Fungus. . . . . . . . . . . . . . . . . . . 112 Halfling', 149, 3),
  ('monster-manual', 'race', 'Deep dwarf . . . . . . . . . . . . . . . . 92 Gargoyle . . . . . . . . . . . . . . . . . 113 Harpy', 150, 3),
  ('monster-manual', 'other', 'Barghest, greater', 23, 3),
  ('monster-manual', 'race', 'Basilisk . . . . . . . . . . . . . . . . . . . 23 Deep halfling . . . . . . . . . . . . . 150 Gauth (beholder). . . . . . . . . . . 26 Hawk', 273, 3),
  ('monster-manual', 'other', 'Bat . . . . . . . . . . . . . . . . . . . . . . 268 Deinonychus (dinosaur) . . . . 60 Gelatinous cube . . . . . . . . . . 201 Hell hound', 151, 3),
  ('monster-manual', 'other', 'Bat, dire . . . . . . . . . . . . . . . . . . . 62 Delver . . . . . . . . . . . . . . . . . . . . 39 Genie . . . . . . . . . . . . . . . . . . . . 114 Hellcat (devil)', 54, 3),
  ('monster-manual', 'other', 'Bear, black . . . . . . . . . . . . . . . 269 Demon. . . . . . . . . . . . . . . . . . . . 40 Ghaele (eladrin). . . . . . . . . . . . 94 Hezrou (demon)', 44, 3),
  ('monster-manual', 'other', 'Derro . . . . . . . . . . . . . . . . . . . . . 49 Ghast . . . . . . . . . . . . . . . . . . . . 119 Hieracosphinx', 234, 3),
  ('monster-manual', 'other', 'Bear, brown', 269, 3),
  ('monster-manual', 'other', 'Bear, dire . . . . . . . . . . . . . . . . . . 63 Destrachan . . . . . . . . . . . . . . . . 49 Ghost . . . . . . . . . . . . . . . . . . . . 116 Hippogriff', 152, 3),
  ('monster-manual', 'other', 'Bear, polar. . . . . . . . . . . . . . . . 269 Devil. . . . . . . . . . . . . . . . . . . . . . 50 Ghoul. . . . . . . . . . . . . . . . . . . . 118 Hill giant', 123, 3),
  ('monster-manual', 'other', 'Bebilith (demon). . . . . . . . . . . 42 Digester. . . . . . . . . . . . . . . . . . . 59 Giant ant . . . . . . . . . . . . . . . . . 284 (lycanthrope)', 174, 3),
  ('monster-manual', 'other', 'Dinosaur . . . . . . . . . . . . . . . . . . 60 Giant bee. . . . . . . . . . . . . . . . . 284 Hobgoblin', 153, 3),
  ('monster-manual', 'other', 'Behir', 25, 3),
  ('monster-manual', 'other', 'Beholder . . . . . . . . . . . . . . . . . . 25 Dire animal. . . . . . . . . . . . . . . . 62 Giant bombardier beetle . . . 284 Homunculus', 154, 3),
  ('monster-manual', 'other', 'Belker . . . . . . . . . . . . . . . . . . . . 27 Displacer beast. . . . . . . . . . . . . 66 Giant constrictor snake . . . . 280 Horned devil (cornugon)', 55, 3),
  ('monster-manual', 'other', 'Bison . . . . . . . . . . . . . . . . . . . . 269 Djinni . . . . . . . . . . . . . . . . . . . 114 Giant crocodile . . . . . . . . . . . 271 Horse', 273, 3),
  ('monster-manual', 'other', 'Black dragon . . . . . . . . . . . . . . 70 Dog. . . . . . . . . . . . . . . . . . . . . . 271 Giant eagle . . . . . . . . . . . . . . . . 93 Hound archon', 16, 3),
  ('monster-manual', 'other', 'Black pudding . . . . . . . . . . . . 201 Dog, riding . . . . . . . . . . . . . . . 272 Giant fire beetle . . . . . . . . . . 285 Hound archon hero', 17, 3),
  ('monster-manual', 'other', 'Blink dog . . . . . . . . . . . . . . . . . 28 Donkey . . . . . . . . . . . . . . . . . . 272 Giant octopus. . . . . . . . . . . . . 276 Howler', 154, 3),
  ('monster-manual', 'other', 'Blue dragon . . . . . . . . . . . . . . . 72 Doppelganger . . . . . . . . . . . . . 67 Giant owl . . . . . . . . . . . . . . . . 205 Hydra', 155, 3),
  ('monster-manual', 'other', 'Blue slaad . . . . . . . . . . . . . . . . 229 Dragon, true . . . . . . . . . . . . . . . 68 Giant praying mantis . . . . . . 285 Hyena', 274, 3),
  ('monster-manual', 'other', 'Boar . . . . . . . . . . . . . . . . . . . . . 270 Dragon turtle . . . . . . . . . . . . . . 88 Giant squid . . . . . . . . . . . . . . . 281 Ice devil (gelugon)', 56, 3),
  ('monster-manual', 'other', 'Boar, dire. . . . . . . . . . . . . . . . . . 63 Dragonne . . . . . . . . . . . . . . . . . 89 Giant stag beetle . . . . . . . . . . 285 Ice mephit', 182, 3),
  ('monster-manual', 'other', 'Bodak. . . . . . . . . . . . . . . . . . . . . 28 Dread wraith . . . . . . . . . . . . . 258 Giant wasp . . . . . . . . . . . . . . . 285 Imp (devil)', 56, 3),
  ('monster-manual', 'other', 'Bone devil (osyluth). . . . . . . . 52 Dretch (demon). . . . . . . . . . . . 42 Gibbering mouther . . . . . . . 126 Inevitable', 158, 3),
  ('monster-manual', 'other', 'Invisible stalker. . . . . . . . . . . 160 Nessian warhound (hell Rhinoceros. . . . . . . . . . . . . . . 278 Triceratops', 61, 4),
  ('monster-manual', 'other', 'Iron golem. . . . . . . . . . . . . . . 136 hound). . . . . . . . . . . . . . . . 151 Roc. . . . . . . . . . . . . . . . . . . . . . 215 Triton', 245, 4),
  ('monster-manual', 'other', 'Janni. . . . . . . . . . . . . . . . . . . . . 116 Night hag. . . . . . . . . . . . . . . . 193 Roper. . . . . . . . . . . . . . . . . . . . 215 Troglodyte', 246, 4),
  ('monster-manual', 'monster', 'Kobold. . . . . . . . . . . . . . . . . . . 161 Nightcrawler. . . . . . . . . . . . . 195 Rust monster. . . . . . . . . . . . . 216 Troll', 247, 4),
  ('monster-manual', 'other', 'Sahuagin. . . . . . . . . . . . . . . . . 217 Troll hunter', 248, 4),
  ('monster-manual', 'other', 'Kolyarut (inevitable). . . . . . 159 Nightmare', 194, 4),
  ('monster-manual', 'other', 'Kraken. . . . . . . . . . . . . . . . . . . 162 Nightshade. . . . . . . . . . . . . . . 195 Salamander. . . . . . . . . . . . . . . 218 Truly horrid umber hulk', 249, 4),
  ('monster-manual', 'other', 'Krenshar. . . . . . . . . . . . . . . . . 163 Nightwalker. . . . . . . . . . . . . . 196 Salt mephit. . . . . . . . . . . . . . . 184 Trumpet archon', 18, 4),
  ('monster-manual', 'other', 'Kuo-toa. . . . . . . . . . . . . . . . . . 163 Nightwing. . . . . . . . . . . . . . . 197 Satyr. . . . . . . . . . . . . . . . . . . . . 219 Tyrannosaurus (dinosaur)', 61, 4),
  ('monster-manual', 'other', 'Lamia. . . . . . . . . . . . . . . . . . . . 165 Nixie . . . . . . . . . . . . . . . . . . . . 235 Sea cat. . . . . . . . . . . . . . . . . . . 220 Umber hulk', 248, 4),
  ('monster-manual', 'other', 'Nymph . . . . . . . . . . . . . . . . . . 197 Sea hag . . . . . . . . . . . . . . . . . . 144 Unicorn', 249, 4),
  ('monster-manual', 'other', 'Lammasu', 165, 4),
  ('monster-manual', 'other', 'Lantern archon. . . . . . . . . . . . 16 Ochre jelly. . . . . . . . . . . . . . . 202 Shadow. . . . . . . . . . . . . . . . . . 221 Vampire', 250, 4),
  ('monster-manual', 'other', 'Lemure (devil). . . . . . . . . . . . . 57 Octopus. . . . . . . . . . . . . . . . . . 276 Shadow mastiff. . . . . . . . . . . 222 Vampire spawn', 253, 4),
  ('monster-manual', 'other', 'Leonal. . . . . . . . . . . . . . . . . . . 142 Ogre. . . . . . . . . . . . . . . . . . . . . 198 Shambling mound. . . . . . . . 222 Vargouille', 254, 4),
  ('monster-manual', 'class', 'Leopard. . . . . . . . . . . . . . . . . . 274 Ogre barbarian. . . . . . . . . . . . 198 Shark. . . . . . . . . . . . . . . . . . . . 279 Violet fungus', 113, 4),
  ('monster-manual', 'other', 'Shark, dire', 64, 4),
  ('monster-manual', 'other', 'Lich. . . . . . . . . . . . . . . . . . . . . 166 Ogre mage . . . . . . . . . . . . . . . 200 Viper snake', 281, 4),
  ('monster-manual', 'other', 'Lillend. . . . . . . . . . . . . . . . . . . 168 Ooze. . . . . . . . . . . . . . . . . . . . . 201 Shield guardian. . . . . . . . . . . 223 Vrock (demon)', 48, 4),
  ('monster-manual', 'other', 'Lion. . . . . . . . . . . . . . . . . . . . . 274 Ooze mephit . . . . . . . . . . . . . 183 Shocker lizard. . . . . . . . . . . . 224 Water elemental', 98, 4),
  ('monster-manual', 'other', 'Lion, dire. . . . . . . . . . . . . . . . . . 63 Orc. . . . . . . . . . . . . . . . . . . . . . 203 Shrieker . . . . . . . . . . . . . . . . . 113 Water mephit', 185, 4),
  ('monster-manual', 'other', 'Lizard. . . . . . . . . . . . . . . . . . . . 274 Orca. . . . . . . . . . . . . . . . . . . . . 283 Silver dragon. . . . . . . . . . . . . . 86 Water naga', 193, 4),
  ('monster-manual', 'other', 'Lizardfolk. . . . . . . . . . . . . . . . 169 Otyugh . . . . . . . . . . . . . . . . . . 204 Skeleton. . . . . . . . . . . . . . . . . 225 Weasel', 282, 4),
  ('monster-manual', 'other', 'Locathah. . . . . . . . . . . . . . . . . 169 Owl . . . . . . . . . . . . . . . . . . . . . 277 Skum. . . . . . . . . . . . . . . . . . . . 228 Weasel, dire', 65, 4),
  ('monster-manual', 'other', 'Lycanthrope. . . . . . . . . . . . . . 170 Owl, giant. . . . . . . . . . . . . . . . 205 Slaad. . . . . . . . . . . . . . . . . . . . . 228 Werebear (lycanthrope)', 170, 4),
  ('monster-manual', 'other', 'Magma mephit. . . . . . . . . . . 183 Owlbear . . . . . . . . . . . . . . . . . 206 Snake. . . . . . . . . . . . . . . . . . . . 279 Wereboar (lycanthrope)', 171, 4),
  ('monster-manual', 'other', 'Magmin. . . . . . . . . . . . . . . . . . 179 Pack lord (displacer beast) . . 66 Solar (angel). . . . . . . . . . . . . . . 12 Wererat (lycanthrope)', 171, 4),
  ('monster-manual', 'other', 'Manta ray. . . . . . . . . . . . . . . . 275 Pegasus . . . . . . . . . . . . . . . . . . 206 Spectre. . . . . . . . . . . . . . . . . . . 232 Weretiger (lycanthrope)', 172, 4),
  ('monster-manual', 'other', 'Manticore. . . . . . . . . . . . . . . . 179 Phantom fungus. . . . . . . . . . 207 Sphinx. . . . . . . . . . . . . . . . . . . 232 Werewolf (lycanthrope)', 173, 4),
  ('monster-manual', 'other', 'Marut (inevitable). . . . . . . . . 159 Phasm. . . . . . . . . . . . . . . . . . . 208 Spirit naga . . . . . . . . . . . . . . . 192 thrope)', 174, 4),
  ('monster-manual', 'other', 'Medusa. . . . . . . . . . . . . . . . . . 180 Pit fiend (devil). . . . . . . . . . . . 57 Sprite. . . . . . . . . . . . . . . . . . . . 235 Whale', 282, 4),
  ('monster-manual', 'other', 'Megaraptor (dinosaur). . . . . . 60 Pixie. . . . . . . . . . . . . . . . . . . . . 236 Squid. . . . . . . . . . . . . . . . . . . . 281 White dragon', 77, 4),
  ('monster-manual', 'other', 'Mephit. . . . . . . . . . . . . . . . . . . 180 Planetar (angel). . . . . . . . . . . . 11 Steam mephit . . . . . . . . . . . . 184 Wight', 255, 4),
  ('monster-manual', 'race', 'Merfolk. . . . . . . . . . . . . . . . . . 185 Planetouched. . . . . . . . . . . . . 209 Stirge. . . . . . . . . . . . . . . . . . . . 236 Wild elf', 104, 4),
  ('monster-manual', 'other', 'Metallic dragons. . . . . . . . . . . 79 Pony. . . . . . . . . . . . . . . . . . . . . 277 Stone giant. . . . . . . . . . . . . . . 124 Will-o’-wisp', 255, 4),
  ('monster-manual', 'other', 'Mimic. . . . . . . . . . . . . . . . . . . 186 Porpoise. . . . . . . . . . . . . . . . . . 278 Stone golem. . . . . . . . . . . . . . 137 Winter wolf', 256, 4),
  ('monster-manual', 'other', 'Mind flayer. . . . . . . . . . . . . . . 186 Pseudodragon . . . . . . . . . . . . 210 Storm giant. . . . . . . . . . . . . . . 125 Wolf', 283, 4),
  ('monster-manual', 'class', 'Mind flayer sorcerer . . . . . . 187 Pureblood (yuan-ti) . . . . . . . 263 Succubus (demon). . . . . . . . . 47 Wolf, dire', 65, 4),
  ('monster-manual', 'race', 'Minotaur. . . . . . . . . . . . . . . . . 188 Purple worm . . . . . . . . . . . . . 211 Svirfneblin (gnome). . . . . . . 132 Wolverine', 283, 4),
  ('monster-manual', 'other', 'Mohrg. . . . . . . . . . . . . . . . . . . 189 Pyrohydra. . . . . . . . . . . . . . . . 156 Swarm. . . . . . . . . . . . . . . . . . . 237 Wolverine, dire', 66, 4),
  ('monster-manual', 'race', 'Monitor lizard. . . . . . . . . . . . 275 Quasit (demon). . . . . . . . . . . . 46 Tallfellow (halfling). . . . . . . 149 Wood elf', 104, 4),
  ('monster-manual', 'other', 'Monkey. . . . . . . . . . . . . . . . . . 276 Rakshasa. . . . . . . . . . . . . . . . . 211 Tarrasque. . . . . . . . . . . . . . . . . 240 Worg', 256, 4),
  ('monster-manual', 'other', 'Monstrous centipede. . . . . . 287 Rast . . . . . . . . . . . . . . . . . . . . . 213 Tendriculos. . . . . . . . . . . . . . . 241 Wraith', 257, 4),
  ('monster-manual', 'other', 'Monstrous scorpion. . . . . . . 287 Rat . . . . . . . . . . . . . . . . . . . . . . 278 Thoqqua . . . . . . . . . . . . . . . . . 242 Wyvern', 259, 4),
  ('monster-manual', 'other', 'Monstrous spider. . . . . . . . . 288 Rat, dire. . . . . . . . . . . . . . . . . . . 64 Tiefling (planetouched). . . . 209 Xill', 259, 4),
  ('monster-manual', 'race', 'Mountain dwarf . . . . . . . . . . . 93 Raven. . . . . . . . . . . . . . . . . . . . 278 Tiger. . . . . . . . . . . . . . . . . . . . . 281 Xorn', 260, 4),
  ('monster-manual', 'other', 'Ravid. . . . . . . . . . . . . . . . . . . . 213 Tiger, dire', 65, 4),
  ('monster-manual', 'other', 'Mule. . . . . . . . . . . . . . . . . . . . . 276 Yeth hound', 260, 4),
  ('monster-manual', 'other', 'Mummy . . . . . . . . . . . . . . . . . 190 Red dragon. . . . . . . . . . . . . . . . 75 Titan. . . . . . . . . . . . . . . . . . . . . 242 Yrthak', 262, 4),
  ('monster-manual', 'other', 'Mummy lord. . . . . . . . . . . . . 191 Red slaad. . . . . . . . . . . . . . . . . 228 Toad. . . . . . . . . . . . . . . . . . . . . 282 Yuan-ti', 262, 4),
  ('monster-manual', 'other', 'Naga. . . . . . . . . . . . . . . . . . . . . 191 Remorhaz. . . . . . . . . . . . . . . . 214 Tojanida. . . . . . . . . . . . . . . . . . 243 Zelekhut (inevitable)', 160, 4),
  ('monster-manual', 'other', 'Nalfeshnee (demon). . . . . . . . 45 Retriever (demon) . . . . . . . . . 46 Treant. . . . . . . . . . . . . . . . . . . . 244 Zombie', 265, 4)
ON CONFLICT (book_slug, content_type, title) DO UPDATE
  SET page_number = EXCLUDED.page_number,
      source_page = EXCLUDED.source_page,
      updated_at = NOW();
