
-- ============================================
-- TABLA DE CONTENIDOS DE LIBROS
-- Referencias a páginas específicas de cada libro
-- ============================================

CREATE TABLE IF NOT EXISTS public.book_contents (
  id BIGSERIAL PRIMARY KEY,
  book_slug TEXT NOT NULL REFERENCES public.books(slug) ON DELETE CASCADE,
  content_type TEXT NOT NULL, -- 'chapter', 'class', 'race', 'feat', 'skill', 'spell', 'equipment', 'monster', 'magic_item'
  title TEXT NOT NULL,
  page_number INTEGER NOT NULL,

  -- Enlaces opcionales a entradas existentes en otras tablas
  class_slug TEXT REFERENCES public.classes(slug),
  race_slug TEXT REFERENCES public.races(slug),
  feat_slug TEXT REFERENCES public.feats(slug),
  skill_slug TEXT REFERENCES public.skills(slug),
  spell_slug TEXT REFERENCES public.spells(slug),

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_book_contents_book ON public.book_contents(book_slug);
CREATE INDEX IF NOT EXISTS idx_book_contents_type ON public.book_contents(content_type);
CREATE INDEX IF NOT EXISTS idx_book_contents_page ON public.book_contents(page_number);

-- Comentarios
COMMENT ON TABLE public.book_contents IS 'Índice de contenidos de todos los libros D&D 3.5';
COMMENT ON COLUMN public.book_contents.content_type IS 'Tipo de contenido: chapter, class, race, feat, skill, spell, equipment, monster, magic_item';
COMMENT ON COLUMN public.book_contents.page_number IS 'Número de página en el PDF del libro';


-- Contenidos de Player's Handbook
INSERT INTO public.book_contents (book_slug, content_type, title, page_number) VALUES
  ('player-handbook', 'chapter', 'Chapter 8: Combat...........................................133 Table 3–13: The Ranger', 46),
  ('player-handbook', 'chapter', 'Chapter 1: Abilities..............................................7 Initiative...........................................................136 Table 3–18: The Wizard', 55),
  ('player-handbook', 'chapter', 'Chapter 2: Races..................................................11 And Distance..............................................146 Table 4–5: Skill Synergies', 66),
  ('player-handbook', 'chapter', 'Elves......................................................................15 Chapter 9: Adventuring................................161 Table 6–2: Deities by Race', 106),
  ('player-handbook', 'chapter', 'Chapter 3: Classes...............................................21 Table 7–1: Random Starting Gold', 111),
  ('player-handbook', 'chapter', 'The Classes..........................................................21 Chapter 10: Magic.............................................169 Table 7–2: Coins', 112),
  ('player-handbook', 'chapter', 'Druid.....................................................................33 Chapter 11: Spells.............................................181 Table 7–8: Goods and Services', 128),
  ('player-handbook', 'chapter', 'Chapter 6: Description', 103),
  ('player-handbook', 'chapter', 'a given spell level. (See the class descriptions in Chapter', 3),
  ('player-handbook', 'class', 'Table 3–12: The Paladin', 43),
  ('player-handbook', 'class', 'Introduction...........................................................4 The Battle Grid................................................133 Table 3–14: Ranger Favored Enemies', 47),
  ('player-handbook', 'class', 'How Combat Works.....................................133 Table 3–15: The Rogue', 49),
  ('player-handbook', 'class', 'Character Creation Summary........................6 Combat Statistics............................................133 Table 3–16: The Sorcerer', 52),
  ('player-handbook', 'class', 'Combat Basics.................................................135 Table 3–17: Sorcerer Spells Known', 54),
  ('player-handbook', 'class', 'Changing Ability Scores.................................10 Injury and Death............................................145 Table 4–3: Difficulty Class Examples', 64),
  ('player-handbook', 'class', 'Dwarves...............................................................14 Class Alignments', 104),
  ('player-handbook', 'class', 'Gnomes................................................................16 Carrying Capacity..........................................161 Table 6–3: Deities by Class', 106),
  ('player-handbook', 'class', 'Class and Level Bonuses.................................21 Casting Spells..................................................169 Table 7–3: Trade Goods', 112),
  ('player-handbook', 'class', 'Class Descriptions............................................23 Arcane Spells...................................................177 Weapon Damage', 114),
  ('player-handbook', 'class', 'Barbarian.............................................................24 Divine Spells....................................................179 Table 7–5: Weapons', 116),
  ('player-handbook', 'class', 'Bard.......................................................................26 Special Abilities..............................................180 Table 7–6: Armor and Shields', 123),
  ('player-handbook', 'class', 'Cleric....................................................................30 Table 7–7: Donning Armor', 123),
  ('player-handbook', 'class', 'Fighter..................................................................37 Bard Spells........................................................181 Table 8–1: Size Modifiers', 134),
  ('player-handbook', 'class', 'Monk....................................................................39 Cleric Spells.....................................................183 Table 8–2: Actions in Combat', 141),
  ('player-handbook', 'class', 'Paladin..................................................................42 Cleric Domains...............................................185 Table 8–3: Tactical Speed', 147),
  ('player-handbook', 'class', 'Ranger..................................................................46 Druid Spells.....................................................189 Table 8–4: Creature Size and Scale', 149),
  ('player-handbook', 'class', 'Rogue....................................................................49 Paladin Spells..................................................191 Table 8–5: Attack Roll Modifiers', 151),
  ('player-handbook', 'class', 'Sorcerer................................................................51 Ranger Spells...................................................191 Table 8–6: Armor Class Modifiers', 151),
  ('player-handbook', 'class', 'Wizard..................................................................55 Sorcerer/Wizard Spells................................192 Table 8–7: Special Attacks', 154),
  ('player-handbook', 'class', 'Multiclass Characters......................................59 Shield Hardness and Hit Points', 158),
  ('player-handbook', 'class', 'Table 3–3: The Barbarian...............................25 and Hit Points', 166),
  ('player-handbook', 'class', 'and Background........................................110 Table 3–5: Bard Spells Known.....................28 of Objects', 166),
  ('player-handbook', 'class', 'Equipping a Character.................................111 Table 3–9: The Fighter....................................39 Burst Items', 166),
  ('player-handbook', 'class', 'creative, be daring, and be true to your character… and most of all, on your class’s list of class skills) for 4 skill points, or as many as', 2),
  ('player-handbook', 'class', 'ASSIGN AND ADJUST ABILITY SCORES rogues and bards get 6 hp; clerics, druids, monks, and rangers get', 8),
  ('player-handbook', 'class', 'worrying about an XP penalty, because rogue is favored', 11),
  ('player-handbook', 'race', 'Choosing a Race................................................11 Combat Modifiers..........................................150 Table 4–6: Example Ability Checks', 66),
  ('player-handbook', 'race', 'Religion: Unlike members of the other common races, humans additional level, since humans are versatile and capable. (The', 4),
  ('player-handbook', 'feat', 'Racial Characteristics......................................11 Special Attacks................................................154 Table 5–1: Feats', 90),
  ('player-handbook', 'feat', 'Acquiring Feats.................................................87 Table 1–1: Ability Modifiers Movement', 164),
  ('player-handbook', 'feat', 'Types of Feats', 87),
  ('player-handbook', 'feat', 'Feat Descriptions', 89),
  ('player-handbook', 'skill', 'Ability Scores.......................................................7 Attacks of Opportunity................................137 Table 4–1: Skill Points per Level', 62),
  ('player-handbook', 'skill', 'The Abilities.........................................................8 Actions in Combat.........................................138 Table 4–2: Skills', 63),
  ('player-handbook', 'skill', 'Skill Summary...................................................61 Fighting Penalties', 160),
  ('player-handbook', 'skill', 'Acquiring Skill Ranks.....................................61 Index......................................................................315 Table 9–1: Carrying Capacity', 162),
  ('player-handbook', 'skill', 'Using Skills........................................................62 Table 9–2: Carrying Loads', 162),
  ('player-handbook', 'skill', 'Skill Descriptions.............................................66 Character Sheet.................................................318 Table 9–3: Movement and Distance', 162),
  ('player-handbook', 'spell', 'and Bonus Spells............................................8 Table 9–6: Mounts and Vehicles', 164),
  ('player-handbook', 'equipment', 'Weapons...........................................................112 Magical Attacks', 177),
  ('player-handbook', 'other', 'Goods and Services........................................126 Unarmed Damage', 41),
  ('player-handbook', 'other', 'Movement, Position, Table 4–4: Example Opposed Checks', 64),
  ('player-handbook', 'other', 'Half-Elves............................................................18 Movement........................................................162 Table 6–4: Random Starting Ages', 109),
  ('player-handbook', 'other', 'Half-Orcs.............................................................18 Exploration......................................................164 Table 6–5: Aging Effects', 109),
  ('player-handbook', 'other', 'Other Rewards................................................168 and Weight', 109),
  ('player-handbook', 'other', 'Appendix: General Guidelines Table 8–9: Turning Undead', 159),
  ('player-handbook', 'other', 'Table 9–4: Hampered Movement', 163),
  ('player-handbook', 'other', 'Prerequisites', 87),
  ('player-handbook', 'other', 'Table 3–1: Base Save and and Illumination', 165),
  ('player-handbook', 'other', 'Table 3–2: Experience and Level- Shield Hardness and Hit Points', 166),
  ('player-handbook', 'other', 'Alignment', 103),
  ('player-handbook', 'other', 'Religion', 106),
  ('player-handbook', 'other', 'Vital Statistics', 109),
  ('player-handbook', 'other', 'Table 3–7: Deities.............................................32 and Hit Points', 166),
  ('player-handbook', 'other', '28–29 +9 — 3 2 2 2 2 1 1 1', 1),
  ('player-handbook', 'other', '30–31 +10 — 3 3 2 2 2 2 1 1', 1),
  ('player-handbook', 'other', '32–33 +11 — 3 3 3 2 2 2 2 1', 1),
  ('player-handbook', 'other', '34–35 +12 — 3 3 3 3 2 2 2 2', 1),
  ('player-handbook', 'other', '36–37 +13 — 4 3 3 3 3 2 2 2', 2),
  ('player-handbook', 'other', '38–39 +14 — 4 4 3 3 3 3 2 2', 2),
  ('player-handbook', 'other', '40–41 +15 — 4 4 4 3 3 3 3 2', 2),
  ('player-handbook', 'other', '42–43 +16 — 4 4 4 4 3 3 3 3', 2),
  ('player-handbook', 'other', '44–45 +17 — 5 4 4 4 4 3 3 3', 3);


-- Contenidos de Dungeon Master's Guide
INSERT INTO public.book_contents (book_slug, content_type, title, page_number) VALUES
  ('dungeon-masters-guide', 'chapter', 'Chapter 1: Running the Game . . . . . . . 5 Sample Traps. . . . . . . . . . . . . . . . . . 70 Creating New Classes', 175),
  ('dungeon-masters-guide', 'chapter', 'Chapter 2: Using the Rules . . . . . . . . . 19 Dungeon Level. . . . . . . . . . . . . . . . 77 Blackguard', 181),
  ('dungeon-masters-guide', 'chapter', 'Describing Spell Effects. . . . . . . . 34 Chapter 4: Nonplayer Characters . . 103 Epic Characters', 206),
  ('dungeon-masters-guide', 'chapter', 'Creating New Spells. . . . . . . . . . . . 35 NPC Classes. . . . . . . . . . . . . . . . . . . . . 107 Chapter 7: Magic Items', 211),
  ('dungeon-masters-guide', 'chapter', 'Chapter 3: Adventures . . . . . . . . . . . . . 43 NPC Attitudes. . . . . . . . . . . . . . . . . . . 128 Rods', 233),
  ('dungeon-masters-guide', 'chapter', 'Site-Based Adventures. . . . . . . . . . . . . 46 Chapter 5: Campaigns. . . . . . . . . . . . . 129 Wands', 245),
  ('dungeon-masters-guide', 'chapter', 'Location . . . . . . . . . . . . . . . . . . . . . . 50 Adventuring on Other Planes. . . . . 147 Chapter 8: Glossary', 289),
  ('dungeon-masters-guide', 'chapter', 'Between Adventures . . . . . . . . . . . . . . 57 Chapter 6: Characters', 169),
  ('dungeon-masters-guide', 'class', 'Contents Miscellaneous Features. . . . . . . . . 63 Class/Race Restrictions', 171),
  ('dungeon-masters-guide', 'class', 'Introduction. . . . . . . . . . . . . . . . . . . . . . . . 4 Traps. . . . . . . . . . . . . . . . . . . . . . . . . . . . . 67 Classes', 174),
  ('dungeon-masters-guide', 'class', 'Elements of a Trap . . . . . . . . . . . . . 68 Modifying Character Classes', 174),
  ('dungeon-masters-guide', 'class', 'What Is a DM?. . . . . . . . . . . . . . . . . . . . . 5 Designing a Trap. . . . . . . . . . . . . . . 74 Prestige Classes', 176),
  ('dungeon-masters-guide', 'class', 'Starting an Encounter. . . . . . . . . . 22 Hills Terrain. . . . . . . . . . . . . . . . . . . 89 Red Wizard', 193),
  ('dungeon-masters-guide', 'class', 'Effect of Weapon Size. . . . . . . . . . 28 Weather. . . . . . . . . . . . . . . . . . . . . . . 93 Gaining Class Benefits', 198),
  ('dungeon-masters-guide', 'race', 'Cave-Ins and Collapses. . . . . . . . . 66 New Races', 171),
  ('dungeon-masters-guide', 'race', 'Illumination. . . . . . . . . . . . . . . . . . . 67 Monsters as Races', 172),
  ('dungeon-masters-guide', 'race', 'Dungeon Terrain. . . . . . . . . . . . . . . . . . 59 Races', 170),
  ('dungeon-masters-guide', 'race', 'Walls . . . . . . . . . . . . . . . . . . . . . . . . . 59 Subraces. . . . . . . . . . . . . . . . . . . . . 170 Index', 317),
  ('dungeon-masters-guide', 'race', 'Doors. . . . . . . . . . . . . . . . . . . . . . . . . 60 Modifying a Common Race. . . . 171 List of Sidebars', 319),
  ('dungeon-masters-guide', 'feat', 'Attack Rolls. . . . . . . . . . . . . . . . . . . 26 Aquatic Terrain . . . . . . . . . . . . . . . . 92 Learning Skills and Feats', 197),
  ('dungeon-masters-guide', 'feat', 'Skill and Ability Checks. . . . . . . . . . . 30 Urban Features. . . . . . . . . . . . . . . . 99 Familiars', 200),
  ('dungeon-masters-guide', 'spell', 'Damage. . . . . . . . . . . . . . . . . . . . . . . 26 Underwater Combat. . . . . . . . . 93 Learning New Spells', 198),
  ('dungeon-masters-guide', 'spell', 'Area Spells. . . . . . . . . . . . . . . . . . . . 28 Encounters. . . . . . . . . . . . . . . . . . 95 Gaining Fixed Hit Points', 198),
  ('dungeon-masters-guide', 'spell', 'in Combat . . . . . . . . . . . . . . . . . . 29 Weapon and Spell Restrictions. . 99 Special Cohorts', 199),
  ('dungeon-masters-guide', 'equipment', 'Splash Weapons . . . . . . . . . . . . . . . 28 Random Wilderness General Downtime', 198),
  ('dungeon-masters-guide', 'equipment', 'Story Awards. . . . . . . . . . . . . . . . . . 40 Commoner. . . . . . . . . . . . . . . . . . . 108 Armor', 216),
  ('dungeon-masters-guide', 'equipment', 'Character Death . . . . . . . . . . . . . . . . . . 41 Expert. . . . . . . . . . . . . . . . . . . . . . . 109 Weapons', 221),
  ('dungeon-masters-guide', 'equipment', 'powers or equipment. No one likes to get something (a new an in-game solution. Nobody said DMing was easy.', 13),
  ('dungeon-masters-guide', 'monster', 'Running a Game Session . . . . . . . . . . 10 Wandering Monsters. . . . . . . . . . . 77 Archmage', 178),
  ('dungeon-masters-guide', 'monster', 'Big and Little Creatures Urban Adventures. . . . . . . . . . . . . . . . . 98 Creating PCs above 1st Level', 199),
  ('dungeon-masters-guide', 'monster', 'Tougher Monsters . . . . . . . . . . . . . 50 Building a Different World', 144),
  ('dungeon-masters-guide', 'magic_item', 'Rewards. . . . . . . . . . . . . . . . . . . . . . . . . . 36 Adept. . . . . . . . . . . . . . . . . . . . . . . . 107 Handling Magic Items', 212),
  ('dungeon-masters-guide', 'magic_item', 'Experience Awards. . . . . . . . . . . . . 36 Aristocrat. . . . . . . . . . . . . . . . . . . . 108 Magic Item Descriptions', 215),
  ('dungeon-masters-guide', 'magic_item', 'Event-Based Adventures. . . . . . . . . . . 47 Establishing a Campaign. . . . . . . . . . 129 Wondrous Items', 246),
  ('dungeon-masters-guide', 'magic_item', 'Challenge Ratings and War and Other Calamities . . . . . . . . 133 Creating Magic Items', 282),
  ('dungeon-masters-guide', 'other', '620-17752-001-EN 9 8 7 6 5 4 3 2', 1),
  ('dungeon-masters-guide', 'other', 'Style of Play . . . . . . . . . . . . . . . . . . . . . . . 7 Dungeon Ecology. . . . . . . . . . . . . . . . . 76 Arcane Archer', 176),
  ('dungeon-masters-guide', 'other', 'Example of Play. . . . . . . . . . . . . . . . . . . . 8 Dungeon Animals. . . . . . . . . . . . . . 76 Arcane Trickster', 177),
  ('dungeon-masters-guide', 'other', 'Random Dungeons. . . . . . . . . . . . . . . . 77 Assassin', 180),
  ('dungeon-masters-guide', 'other', 'More Movement Rules. . . . . . . . . . . . 19 The Map and the Key. . . . . . . . . . . 77 Dragon Disciple', 183),
  ('dungeon-masters-guide', 'other', 'Movement and the Grid. . . . . . . . 19 Random Dungeon Encounters. . 78 Duelist', 185),
  ('dungeon-masters-guide', 'other', 'Moving in Three Dimensions. . . 20 A Sample Adventure . . . . . . . . . . . . . . 78 Dwarven Defender', 186),
  ('dungeon-masters-guide', 'other', 'Evasion and Pursuit. . . . . . . . . . . . 20 Statistics Blocks. . . . . . . . . . . . . . . . . . . 85 Eldritch Knight', 187),
  ('dungeon-masters-guide', 'other', 'Moving around in Squares. . . . . . 20 Wilderness Adventures. . . . . . . . . . . . 86 Hierophant', 188),
  ('dungeon-masters-guide', 'other', 'Bonus Types. . . . . . . . . . . . . . . . . . . . . . 21 Getting Lost. . . . . . . . . . . . . . . . . . . 86 Horizon Walker', 189),
  ('dungeon-masters-guide', 'other', 'Combat . . . . . . . . . . . . . . . . . . . . . . . . . . 21 Forest Terrain. . . . . . . . . . . . . . . . . . 87 Loremaster', 190),
  ('dungeon-masters-guide', 'other', 'Line of Sight . . . . . . . . . . . . . . . . . . 21 Marsh Terrain . . . . . . . . . . . . . . . . . 88 Mystic Theurge', 192),
  ('dungeon-masters-guide', 'other', 'New Combatants . . . . . . . . . . . . . . 23 Mountain Terrain. . . . . . . . . . . . . . 89 Shadowdancer', 194),
  ('dungeon-masters-guide', 'other', 'Keeping Things Moving. . . . . . . . 24 Desert Terrain . . . . . . . . . . . . . . . . . 91 Thaumaturgist', 196),
  ('dungeon-masters-guide', 'other', 'Combat Actions. . . . . . . . . . . . . . . . 25 Plains Terrain. . . . . . . . . . . . . . . . . . 91 How PCs Improve', 197),
  ('dungeon-masters-guide', 'other', 'Saving Throws. . . . . . . . . . . . . . . . . . . . 33 Urban Encounters. . . . . . . . . . . . 101 Mounts', 204),
  ('dungeon-masters-guide', 'other', 'Adjudicating Magic . . . . . . . . . . . . . . . 34 Animal Companions', 205),
  ('dungeon-masters-guide', 'other', 'Handling Divinations. . . . . . . . . . 34 Everyone in the World', 103),
  ('dungeon-masters-guide', 'other', 'Making a New Character. . . . . . . 42 Warrior. . . . . . . . . . . . . . . . . . . . . . 109 Potions and Oils', 229),
  ('dungeon-masters-guide', 'other', 'NPC Statistics. . . . . . . . . . . . . . . . . . . 110 Rings', 229),
  ('dungeon-masters-guide', 'other', 'Motivation . . . . . . . . . . . . . . . . . . . . . . . 43 Fleshing out NPCs. . . . . . . . . . . . . . . 128 Scrolls', 237),
  ('dungeon-masters-guide', 'other', 'Structure. . . . . . . . . . . . . . . . . . . . . . . . . 44 Staffs', 243),
  ('dungeon-masters-guide', 'other', 'The End (?). . . . . . . . . . . . . . . . . . . . . . . 48 Maintaining a Campaign . . . . . . . . . 130 Intelligent Items', 268),
  ('dungeon-masters-guide', 'other', 'Encounters. . . . . . . . . . . . . . . . . . . . . . . 48 Characters and the World Cursed Items', 272),
  ('dungeon-masters-guide', 'other', 'Tailored or Status Quo. . . . . . . . . . 48 around Them. . . . . . . . . . . . . . . . . . 131 Artifacts', 277),
  ('dungeon-masters-guide', 'other', 'Encounter Levels. . . . . . . . . . . . 48 Other Campaign Issues. . . . . . . . . . . 134 Masterwork Items', 283),
  ('dungeon-masters-guide', 'other', 'Difficulty . . . . . . . . . . . . . . . . . . . . . 49 World-Building. . . . . . . . . . . . . . . . . . 135 Special Materials', 283),
  ('dungeon-masters-guide', 'other', 'Rewards and Behavior. . . . . . . . . . 50 Plane Descriptions. . . . . . . . . . . . . . . 151 Special Abilities', 289),
  ('dungeon-masters-guide', 'other', 'Treasure. . . . . . . . . . . . . . . . . . . . . . . . . . 51 Creating a Cosmology. . . . . . . . . . . . 167 Condition Summary', 300),
  ('dungeon-masters-guide', 'other', 'Bringing Adventures Together. . . . . . 56 The Environment', 302),
  ('dungeon-masters-guide', 'other', 'The Dungeon. . . . . . . . . . . . . . . . . . . . . 57 Ability Scores. . . . . . . . . . . . . . . . . . . . 169 Visual Aids', 305),
  ('dungeon-masters-guide', 'other', 'Rooms. . . . . . . . . . . . . . . . . . . . . . . . 62 Changes through Addition List of Numbered Tables', 320),
  ('dungeon-masters-guide', 'other', 'Corridors . . . . . . . . . . . . . . . . . . . . . 63 and Subtraction', 171),
  ('dungeon-masters-guide', 'other', 'Jozan: Okay. I do. What happens? [Looks at the DM.] center. The formation is clearly a limed-over skeleton—it must', 9),
  ('dungeon-masters-guide', 'other', 'a Listen check for the ghouls at the far end of the secret corridor—an', 18),
  ('dungeon-masters-guide', 'other', 'group’s answers ahead of time will save you from arguments later. playing and spoils the suspension of disbelief.', 11);


-- Contenidos de Monster Manual
INSERT INTO public.book_contents (book_slug, content_type, title, page_number) VALUES
  ('monster-manual', 'chapter', 'Introduction . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5 Chapter 4: Improving Monsters', 290),
  ('monster-manual', 'chapter', 'Chapter 1: Monsters A to Z . . . . . . . . . . . . . . . 8 Chapter 5: Making Monsters', 295),
  ('monster-manual', 'chapter', 'Chapter 2: Animals . . . . . . . . . . . . . . . . . . . . 268 Chapter 6: Monster Skills and Feats', 303),
  ('monster-manual', 'chapter', 'Chapter 3: Vermin . . . . . . . . . . . . . . . . . . . . . 284 Chapter 7: Glossary', 305),
  ('monster-manual', 'class', 'Beholder . . . . . . . . . . . . . . . . . . 25 Dire animal. . . . . . . . . . . . . . . . 62 Giant bombardier beetle . . . 284 Homunculus', 154),
  ('monster-manual', 'class', 'Leopard. . . . . . . . . . . . . . . . . . 274 Ogre barbarian. . . . . . . . . . . . 198 Shark. . . . . . . . . . . . . . . . . . . . 279 Violet fungus', 113),
  ('monster-manual', 'class', 'Mind flayer sorcerer . . . . . . 187 Pureblood (yuan-ti) . . . . . . . 263 Succubus (demon). . . . . . . . . 47 Wolf, dire', 65),
  ('monster-manual', 'class', 'Monkey. . . . . . . . . . . . . . . . . . 276 Rakshasa. . . . . . . . . . . . . . . . . 211 Tarrasque. . . . . . . . . . . . . . . . . 240 Worg', 256),
  ('monster-manual', 'class', 'Armor Class: 16 (–2 size, +1 Dex, +7 natural), 18 (–2 size, +3 Dex, +7 natural), touch 11, flat-footed', 15),
  ('monster-manual', 'class', 'Spot +32, Survival +7 (+9 following tracks), Use Rope +5 (+7 Typical Cleric Spells Prepared(6/8/8/8/7/7/6/6/5/5; save DC', 17),
  ('monster-manual', 'class', 'Armor Class:18 (–1 size, +9 natural), touch 9, flat-footed', 18),
  ('monster-manual', 'race', 'Aboleth . . . . . . . . . . . . . . . . . . . . 8 Brass dragon. . . . . . . . . . . . . . . 79 Drow (elf ). . . . . . . . . . . . . . . . 103 Githyanki', 127),
  ('monster-manual', 'race', 'Abomination (yuan-ti). . . . . 264 Bugbear . . . . . . . . . . . . . . . . . . . 29 Duergar (dwarf ) . . . . . . . . . . . 92 Glabrezu (demon)', 43),
  ('monster-manual', 'race', 'Achaierai . . . . . . . . . . . . . . . . . . . 9 Cachalot whale . . . . . . . . . . . 283 Dwarf . . . . . . . . . . . . . . . . . . . . . 91 Gnome', 131),
  ('monster-manual', 'race', 'Angel . . . . . . . . . . . . . . . . . . . . . 10 Celestial charger (unicorn). 250 Efreeti . . . . . . . . . . . . . . . . . . . 115 Gray elf', 104),
  ('monster-manual', 'race', 'Aquatic elf . . . . . . . . . . . . . . . 103 Chimera . . . . . . . . . . . . . . . . . . 34 Elf . . . . . . . . . . . . . . . . . . . . . . . 101 Green hag', 143),
  ('monster-manual', 'race', 'Badger . . . . . . . . . . . . . . . . . . . 268 Crocodile . . . . . . . . . . . . . . . . 271 Forest gnome . . . . . . . . . . . . . 132 Half-dragon', 146),
  ('monster-manual', 'race', 'Badger, dire . . . . . . . . . . . . . . . 62 Criosphinx . . . . . . . . . . . . . . . 233 Formian. . . . . . . . . . . . . . . . . . 108 Half-elf', 102),
  ('monster-manual', 'race', 'Barghest . . . . . . . . . . . . . . . . . . 22 Death slaad . . . . . . . . . . . . . . . 231 Fungus. . . . . . . . . . . . . . . . . . . 112 Halfling', 149),
  ('monster-manual', 'race', 'Barghest, greater . . . . . . . . . . . 23 Deep dwarf . . . . . . . . . . . . . . . . 92 Gargoyle . . . . . . . . . . . . . . . . . 113 Harpy', 150),
  ('monster-manual', 'race', 'Basilisk . . . . . . . . . . . . . . . . . . . 23 Deep halfling . . . . . . . . . . . . . 150 Gauth (beholder). . . . . . . . . . . 26 Hawk', 273),
  ('monster-manual', 'race', 'Merfolk. . . . . . . . . . . . . . . . . . 185 Planetouched. . . . . . . . . . . . . 209 Stirge. . . . . . . . . . . . . . . . . . . . 236 Wild elf', 104),
  ('monster-manual', 'race', 'Minotaur. . . . . . . . . . . . . . . . . 188 Purple worm . . . . . . . . . . . . . 211 Svirfneblin (gnome). . . . . . . 132 Wolverine', 283),
  ('monster-manual', 'race', 'Monitor lizard. . . . . . . . . . . . 275 Quasit (demon). . . . . . . . . . . . 46 Tallfellow (halfling). . . . . . . 149 Wood elf', 104),
  ('monster-manual', 'race', 'Mountain dwarf . . . . . . . . . . . 93 Raven. . . . . . . . . . . . . . . . . . . . 278 Tiger. . . . . . . . . . . . . . . . . . . . . 281 Xorn', 260),
  ('monster-manual', 'spell', 'Special Qualities:Darkvision 60 ft., spell resistance', 19),
  ('monster-manual', 'monster', 'Animated object . . . . . . . . . . . 13 Celestial creature. . . . . . . . . . . 31 Eladrin. . . . . . . . . . . . . . . . . . . . 93 Gray ooze', 202),
  ('monster-manual', 'monster', 'Athach . . . . . . . . . . . . . . . . . . . . 21 Cloud giant. . . . . . . . . . . . . . . 120 Fiendish creature . . . . . . . . . 107 Guardian naga', 192),
  ('monster-manual', 'monster', 'Kobold. . . . . . . . . . . . . . . . . . . 161 Nightcrawler. . . . . . . . . . . . . 195 Rust monster. . . . . . . . . . . . . 216 Troll', 247),
  ('monster-manual', 'monster', 'ble affliction. A creature hit by a tentacle must succeed on a DC', 19),
  ('monster-manual', 'monster', '+4 resistance bonus on saving throws to anyone within 20 feet of the round with its mace, that creature must succeed on a DC', 22),
  ('monster-manual', 'other', 'Aasimar (planetouched) . . . 209 Bralani (eladrin) . . . . . . . . . . . 93 Drider . . . . . . . . . . . . . . . . . . . . 89 Girallon', 126),
  ('monster-manual', 'other', 'Aboleth mage. . . . . . . . . . . . . . . 8 Bronze dragon . . . . . . . . . . . . . 80 Dryad . . . . . . . . . . . . . . . . . . . . . 90 Githzerai', 129),
  ('monster-manual', 'other', 'Abyssal greater basilisk . . . . . 24 Bulette . . . . . . . . . . . . . . . . . . . . 30 Dust mephit . . . . . . . . . . . . . . 181 Gnoll', 130),
  ('monster-manual', 'other', 'Air elemental . . . . . . . . . . . . . . 95 Camel . . . . . . . . . . . . . . . . . . . 270 Eagle . . . . . . . . . . . . . . . . . . . . 272 Goblin', 133),
  ('monster-manual', 'other', 'Air mephit . . . . . . . . . . . . . . . 181 Carrion crawler . . . . . . . . . . . . 30 Eagle, giant . . . . . . . . . . . . . . . . 93 Gold dragon', 84),
  ('monster-manual', 'other', 'Allip . . . . . . . . . . . . . . . . . . . . . . 10 Cat . . . . . . . . . . . . . . . . . . . . . . 270 Earth elemental. . . . . . . . . . . . 98 Golem', 134),
  ('monster-manual', 'other', 'Androsphinx . . . . . . . . . . . . . 232 Cauchemar (nightmare) . . . 195 Earth mephit . . . . . . . . . . . . . 182 Gorgon', 137),
  ('monster-manual', 'other', 'Ankheg . . . . . . . . . . . . . . . . . . . 14 Centaur . . . . . . . . . . . . . . . . . . . 32 Elasmosaurus (dinosaur) . . . . 60 Gray render', 138),
  ('monster-manual', 'other', 'Annis (hag). . . . . . . . . . . . . . . 143 Chain devil (kyton) . . . . . . . . 53 Elder black pudding. . . . . . . 201 Gray slaad', 231),
  ('monster-manual', 'other', 'Ape . . . . . . . . . . . . . . . . . . . . . . 268 Chaos beast. . . . . . . . . . . . . . . . 33 Elemental . . . . . . . . . . . . . . . . . 95 Greater barghest', 23),
  ('monster-manual', 'other', 'Ape, dire . . . . . . . . . . . . . . . . . . 62 Cheetah. . . . . . . . . . . . . . . . . . 271 Elephant . . . . . . . . . . . . . . . . . 272 Green dragon', 74),
  ('monster-manual', 'other', 'Aranea . . . . . . . . . . . . . . . . . . . . 15 Choker. . . . . . . . . . . . . . . . . . . . 34 Erinyes (devil) . . . . . . . . . . . . . 54 Green slaad', 230),
  ('monster-manual', 'other', 'Archon. . . . . . . . . . . . . . . . . . . . 16 Chromatic dragons. . . . . . . . . 70 Ethereal filcher . . . . . . . . . . . 104 Grick', 139),
  ('monster-manual', 'other', 'Arrowhawk. . . . . . . . . . . . . . . . 19 Chuul. . . . . . . . . . . . . . . . . . . . . 35 Ethereal marauder . . . . . . . . 105 Griffon', 139),
  ('monster-manual', 'other', 'Assassin vine . . . . . . . . . . . . . . 20 Clay golem . . . . . . . . . . . . . . . 134 Ettercap. . . . . . . . . . . . . . . . . . 106 Grig', 235),
  ('monster-manual', 'other', 'Astral deva (angel) . . . . . . . . . 11 Cloaker . . . . . . . . . . . . . . . . . . . 36 Ettin . . . . . . . . . . . . . . . . . . . . . 106 Grimlock', 140),
  ('monster-manual', 'other', 'Avoral (guardinal). . . . . . . . . 141 Cockatrice. . . . . . . . . . . . . . . . . 37 Fire elemental . . . . . . . . . . . . . 98 Guardinal', 141),
  ('monster-manual', 'other', 'Azer . . . . . . . . . . . . . . . . . . . . . . 21 Constrictor snake . . . . . . . . . 279 Fire giant. . . . . . . . . . . . . . . . . 121 Gynosphinx', 233),
  ('monster-manual', 'other', 'Babau (demon) . . . . . . . . . . . . 40 Copper dragon. . . . . . . . . . . . . 82 Fire mephit. . . . . . . . . . . . . . . 182 Hag', 143),
  ('monster-manual', 'other', 'Baboon . . . . . . . . . . . . . . . . . . 268 Couatl . . . . . . . . . . . . . . . . . . . . 37 Flesh golem . . . . . . . . . . . . . . 135 Half-celestial', 144),
  ('monster-manual', 'other', 'Baleen whale . . . . . . . . . . . . . 282 Cryohydra. . . . . . . . . . . . . . . . 157 Frost giant. . . . . . . . . . . . . . . . 122 Half-fiend', 147),
  ('monster-manual', 'other', 'Balor (demon) . . . . . . . . . . . . . 40 Dark naga . . . . . . . . . . . . . . . . 191 Frost giant jarl . . . . . . . . . . . . 123 Half-orc', 204),
  ('monster-manual', 'other', 'Barbed devil (hamatula) . . . . 51 Darkmantle. . . . . . . . . . . . . . . . 38 Frost worm. . . . . . . . . . . . . . . 111 Halfblood (yuan-ti)', 264),
  ('monster-manual', 'other', 'Bat . . . . . . . . . . . . . . . . . . . . . . 268 Deinonychus (dinosaur) . . . . 60 Gelatinous cube . . . . . . . . . . 201 Hell hound', 151),
  ('monster-manual', 'other', 'Bat, dire . . . . . . . . . . . . . . . . . . . 62 Delver . . . . . . . . . . . . . . . . . . . . 39 Genie . . . . . . . . . . . . . . . . . . . . 114 Hellcat (devil)', 54),
  ('monster-manual', 'other', 'Bear, black . . . . . . . . . . . . . . . 269 Demon. . . . . . . . . . . . . . . . . . . . 40 Ghaele (eladrin). . . . . . . . . . . . 94 Hezrou (demon)', 44),
  ('monster-manual', 'other', 'Bear, brown . . . . . . . . . . . . . . 269 Derro . . . . . . . . . . . . . . . . . . . . . 49 Ghast . . . . . . . . . . . . . . . . . . . . 119 Hieracosphinx', 234),
  ('monster-manual', 'other', 'Bear, dire . . . . . . . . . . . . . . . . . . 63 Destrachan . . . . . . . . . . . . . . . . 49 Ghost . . . . . . . . . . . . . . . . . . . . 116 Hippogriff', 152),
  ('monster-manual', 'other', 'Bear, polar. . . . . . . . . . . . . . . . 269 Devil. . . . . . . . . . . . . . . . . . . . . . 50 Ghoul. . . . . . . . . . . . . . . . . . . . 118 Hill giant', 123),
  ('monster-manual', 'other', 'Bebilith (demon). . . . . . . . . . . 42 Digester. . . . . . . . . . . . . . . . . . . 59 Giant ant . . . . . . . . . . . . . . . . . 284 (lycanthrope)', 174),
  ('monster-manual', 'other', 'Behir . . . . . . . . . . . . . . . . . . . . . 25 Dinosaur . . . . . . . . . . . . . . . . . . 60 Giant bee. . . . . . . . . . . . . . . . . 284 Hobgoblin', 153),
  ('monster-manual', 'other', 'Belker . . . . . . . . . . . . . . . . . . . . 27 Displacer beast. . . . . . . . . . . . . 66 Giant constrictor snake . . . . 280 Horned devil (cornugon)', 55),
  ('monster-manual', 'other', 'Bison . . . . . . . . . . . . . . . . . . . . 269 Djinni . . . . . . . . . . . . . . . . . . . 114 Giant crocodile . . . . . . . . . . . 271 Horse', 273),
  ('monster-manual', 'other', 'Black dragon . . . . . . . . . . . . . . 70 Dog. . . . . . . . . . . . . . . . . . . . . . 271 Giant eagle . . . . . . . . . . . . . . . . 93 Hound archon', 16),
  ('monster-manual', 'other', 'Black pudding . . . . . . . . . . . . 201 Dog, riding . . . . . . . . . . . . . . . 272 Giant fire beetle . . . . . . . . . . 285 Hound archon hero', 17),
  ('monster-manual', 'other', 'Blink dog . . . . . . . . . . . . . . . . . 28 Donkey . . . . . . . . . . . . . . . . . . 272 Giant octopus. . . . . . . . . . . . . 276 Howler', 154),
  ('monster-manual', 'other', 'Blue dragon . . . . . . . . . . . . . . . 72 Doppelganger . . . . . . . . . . . . . 67 Giant owl . . . . . . . . . . . . . . . . 205 Hydra', 155),
  ('monster-manual', 'other', 'Blue slaad . . . . . . . . . . . . . . . . 229 Dragon, true . . . . . . . . . . . . . . . 68 Giant praying mantis . . . . . . 285 Hyena', 274),
  ('monster-manual', 'other', 'Boar . . . . . . . . . . . . . . . . . . . . . 270 Dragon turtle . . . . . . . . . . . . . . 88 Giant squid . . . . . . . . . . . . . . . 281 Ice devil (gelugon)', 56),
  ('monster-manual', 'other', 'Boar, dire. . . . . . . . . . . . . . . . . . 63 Dragonne . . . . . . . . . . . . . . . . . 89 Giant stag beetle . . . . . . . . . . 285 Ice mephit . . . . . . . . . . . . . . . 182', 3),
  ('monster-manual', 'other', 'Bodak. . . . . . . . . . . . . . . . . . . . . 28 Dread wraith . . . . . . . . . . . . . 258 Giant wasp . . . . . . . . . . . . . . . 285 Imp (devil)', 56),
  ('monster-manual', 'other', 'Bone devil (osyluth). . . . . . . . 52 Dretch (demon). . . . . . . . . . . . 42 Gibbering mouther . . . . . . . 126 Inevitable', 158),
  ('monster-manual', 'other', 'Invisible stalker. . . . . . . . . . . 160 Nessian warhound (hell Rhinoceros. . . . . . . . . . . . . . . 278 Triceratops', 61),
  ('monster-manual', 'other', 'Iron golem. . . . . . . . . . . . . . . 136 hound). . . . . . . . . . . . . . . . 151 Roc. . . . . . . . . . . . . . . . . . . . . . 215 Triton', 245),
  ('monster-manual', 'other', 'Janni. . . . . . . . . . . . . . . . . . . . . 116 Night hag. . . . . . . . . . . . . . . . 193 Roper. . . . . . . . . . . . . . . . . . . . 215 Troglodyte', 246),
  ('monster-manual', 'other', 'Kolyarut (inevitable). . . . . . 159 Nightmare . . . . . . . . . . . . . . . 194 Sahuagin. . . . . . . . . . . . . . . . . 217 Troll hunter', 248),
  ('monster-manual', 'other', 'Kraken. . . . . . . . . . . . . . . . . . . 162 Nightshade. . . . . . . . . . . . . . . 195 Salamander. . . . . . . . . . . . . . . 218 Truly horrid umber hulk', 249),
  ('monster-manual', 'other', 'Krenshar. . . . . . . . . . . . . . . . . 163 Nightwalker. . . . . . . . . . . . . . 196 Salt mephit. . . . . . . . . . . . . . . 184 Trumpet archon', 18),
  ('monster-manual', 'other', 'Kuo-toa. . . . . . . . . . . . . . . . . . 163 Nightwing. . . . . . . . . . . . . . . 197 Satyr. . . . . . . . . . . . . . . . . . . . . 219 Tyrannosaurus (dinosaur)', 61),
  ('monster-manual', 'other', 'Lamia. . . . . . . . . . . . . . . . . . . . 165 Nixie . . . . . . . . . . . . . . . . . . . . 235 Sea cat. . . . . . . . . . . . . . . . . . . 220 Umber hulk', 248),
  ('monster-manual', 'other', 'Lammasu . . . . . . . . . . . . . . . . 165 Nymph . . . . . . . . . . . . . . . . . . 197 Sea hag . . . . . . . . . . . . . . . . . . 144 Unicorn', 249),
  ('monster-manual', 'other', 'Lantern archon. . . . . . . . . . . . 16 Ochre jelly. . . . . . . . . . . . . . . 202 Shadow. . . . . . . . . . . . . . . . . . 221 Vampire', 250),
  ('monster-manual', 'other', 'Lemure (devil). . . . . . . . . . . . . 57 Octopus. . . . . . . . . . . . . . . . . . 276 Shadow mastiff. . . . . . . . . . . 222 Vampire spawn', 253),
  ('monster-manual', 'other', 'Leonal. . . . . . . . . . . . . . . . . . . 142 Ogre. . . . . . . . . . . . . . . . . . . . . 198 Shambling mound. . . . . . . . 222 Vargouille', 254),
  ('monster-manual', 'other', 'Lich. . . . . . . . . . . . . . . . . . . . . 166 Ogre mage . . . . . . . . . . . . . . . 200 Shark, dire. . . . . . . . . . . . . . . . . 64 Viper snake', 281),
  ('monster-manual', 'other', 'Lillend. . . . . . . . . . . . . . . . . . . 168 Ooze. . . . . . . . . . . . . . . . . . . . . 201 Shield guardian. . . . . . . . . . . 223 Vrock (demon)', 48),
  ('monster-manual', 'other', 'Lion. . . . . . . . . . . . . . . . . . . . . 274 Ooze mephit . . . . . . . . . . . . . 183 Shocker lizard. . . . . . . . . . . . 224 Water elemental', 98),
  ('monster-manual', 'other', 'Lion, dire. . . . . . . . . . . . . . . . . . 63 Orc. . . . . . . . . . . . . . . . . . . . . . 203 Shrieker . . . . . . . . . . . . . . . . . 113 Water mephit', 185),
  ('monster-manual', 'other', 'Lizard. . . . . . . . . . . . . . . . . . . . 274 Orca. . . . . . . . . . . . . . . . . . . . . 283 Silver dragon. . . . . . . . . . . . . . 86 Water naga', 193),
  ('monster-manual', 'other', 'Lizardfolk. . . . . . . . . . . . . . . . 169 Otyugh . . . . . . . . . . . . . . . . . . 204 Skeleton. . . . . . . . . . . . . . . . . 225 Weasel', 282),
  ('monster-manual', 'other', 'Locathah. . . . . . . . . . . . . . . . . 169 Owl . . . . . . . . . . . . . . . . . . . . . 277 Skum. . . . . . . . . . . . . . . . . . . . 228 Weasel, dire', 65),
  ('monster-manual', 'other', 'Lycanthrope. . . . . . . . . . . . . . 170 Owl, giant. . . . . . . . . . . . . . . . 205 Slaad. . . . . . . . . . . . . . . . . . . . . 228 Werebear (lycanthrope)', 170),
  ('monster-manual', 'other', 'Magma mephit. . . . . . . . . . . 183 Owlbear . . . . . . . . . . . . . . . . . 206 Snake. . . . . . . . . . . . . . . . . . . . 279 Wereboar (lycanthrope)', 171),
  ('monster-manual', 'other', 'Magmin. . . . . . . . . . . . . . . . . . 179 Pack lord (displacer beast) . . 66 Solar (angel). . . . . . . . . . . . . . . 12 Wererat (lycanthrope)', 171),
  ('monster-manual', 'other', 'Manta ray. . . . . . . . . . . . . . . . 275 Pegasus . . . . . . . . . . . . . . . . . . 206 Spectre. . . . . . . . . . . . . . . . . . . 232 Weretiger (lycanthrope)', 172),
  ('monster-manual', 'other', 'Manticore. . . . . . . . . . . . . . . . 179 Phantom fungus. . . . . . . . . . 207 Sphinx. . . . . . . . . . . . . . . . . . . 232 Werewolf (lycanthrope)', 173),
  ('monster-manual', 'other', 'Marut (inevitable). . . . . . . . . 159 Phasm. . . . . . . . . . . . . . . . . . . 208 Spirit naga . . . . . . . . . . . . . . . 192 thrope)', 174),
  ('monster-manual', 'other', 'Medusa. . . . . . . . . . . . . . . . . . 180 Pit fiend (devil). . . . . . . . . . . . 57 Sprite. . . . . . . . . . . . . . . . . . . . 235 Whale', 282),
  ('monster-manual', 'other', 'Megaraptor (dinosaur). . . . . . 60 Pixie. . . . . . . . . . . . . . . . . . . . . 236 Squid. . . . . . . . . . . . . . . . . . . . 281 White dragon', 77),
  ('monster-manual', 'other', 'Mephit. . . . . . . . . . . . . . . . . . . 180 Planetar (angel). . . . . . . . . . . . 11 Steam mephit . . . . . . . . . . . . 184 Wight', 255),
  ('monster-manual', 'other', 'Metallic dragons. . . . . . . . . . . 79 Pony. . . . . . . . . . . . . . . . . . . . . 277 Stone giant. . . . . . . . . . . . . . . 124 Will-o’-wisp', 255),
  ('monster-manual', 'other', 'Mimic. . . . . . . . . . . . . . . . . . . 186 Porpoise. . . . . . . . . . . . . . . . . . 278 Stone golem. . . . . . . . . . . . . . 137 Winter wolf', 256),
  ('monster-manual', 'other', 'Mind flayer. . . . . . . . . . . . . . . 186 Pseudodragon . . . . . . . . . . . . 210 Storm giant. . . . . . . . . . . . . . . 125 Wolf', 283),
  ('monster-manual', 'other', 'Mohrg. . . . . . . . . . . . . . . . . . . 189 Pyrohydra. . . . . . . . . . . . . . . . 156 Swarm. . . . . . . . . . . . . . . . . . . 237 Wolverine, dire', 66),
  ('monster-manual', 'other', 'Monstrous centipede. . . . . . 287 Rast . . . . . . . . . . . . . . . . . . . . . 213 Tendriculos. . . . . . . . . . . . . . . 241 Wraith', 257),
  ('monster-manual', 'other', 'Monstrous scorpion. . . . . . . 287 Rat . . . . . . . . . . . . . . . . . . . . . . 278 Thoqqua . . . . . . . . . . . . . . . . . 242 Wyvern', 259),
  ('monster-manual', 'other', 'Monstrous spider. . . . . . . . . 288 Rat, dire. . . . . . . . . . . . . . . . . . . 64 Tiefling (planetouched). . . . 209 Xill', 259),
  ('monster-manual', 'other', 'Mule. . . . . . . . . . . . . . . . . . . . . 276 Ravid. . . . . . . . . . . . . . . . . . . . 213 Tiger, dire. . . . . . . . . . . . . . . . . 65 Yeth hound', 260),
  ('monster-manual', 'other', 'Mummy . . . . . . . . . . . . . . . . . 190 Red dragon. . . . . . . . . . . . . . . . 75 Titan. . . . . . . . . . . . . . . . . . . . . 242 Yrthak', 262),
  ('monster-manual', 'other', 'Mummy lord. . . . . . . . . . . . . 191 Red slaad. . . . . . . . . . . . . . . . . 228 Toad. . . . . . . . . . . . . . . . . . . . . 282 Yuan-ti', 262),
  ('monster-manual', 'other', 'Naga. . . . . . . . . . . . . . . . . . . . . 191 Remorhaz. . . . . . . . . . . . . . . . 214 Tojanida. . . . . . . . . . . . . . . . . . 243 Zelekhut (inevitable)', 160),
  ('monster-manual', 'other', 'Nalfeshnee (demon). . . . . . . . 45 Retriever (demon) . . . . . . . . . 46 Treant. . . . . . . . . . . . . . . . . . . . 244 Zombie', 265),
  ('monster-manual', 'other', 'continued from page', 4),
  ('monster-manual', 'other', 'slaadi, titan. centipedes, monstrous scorpions, monstrous spiders, spider swarm.', 5),
  ('monster-manual', 'other', 'are made with a –5 penalty to the attack roll, no matter how many throws against special abilities have DCs calculated as follows:', 10),
  ('monster-manual', 'other', 'flat-footed', 19),
  ('monster-manual', 'other', 'Abilities:Str 19, Dex 13, Con 14, Int 11, Wis 14, Cha', 16),
  ('monster-manual', 'other', 'touch 9, flat-footed', 15),
  ('monster-manual', 'other', 'Int 15, Wis 17, Cha 17 Int 20, Wis 16, Cha', 14),
  ('monster-manual', 'other', 'Challenge Rating: 7', 17),
  ('monster-manual', 'other', 'Speed:50 ft. (10 squares), fly 100 ft. (good) flat-footed', 28),
  ('monster-manual', 'other', 'low-light vision, immunity to acid, cold, and petrification, protective aura, regeneration 10, resistance to electricity', 10),
  ('monster-manual', 'other', 'Saves:Fort +14 (+18 against poison), Ref +12, Will +12 Abilities:Str 25, Dex 19, Con 20, Int 22, Wis 23, Cha', 22),
  ('monster-manual', 'other', 'flat-footed 12 touch 12, flat-footed 13 touch 10, flat-footed', 14),
  ('monster-manual', 'other', 'Int —, Wis 1, Cha 1 Int —, Wis 1, Cha 1 Int —, Wis 1, Cha', 1),
  ('monster-manual', 'other', 'Challenge Rating: 1/2 1', 2),
  ('monster-manual', 'other', 'Alignment: Always neutral Always neutral Always neutral', 13),
  ('monster-manual', 'other', 'Abilities:Str 21, Dex 10, Con 17, Int 1, Wis 13, Cha', 6),
  ('monster-manual', 'other', 'flat-footed 14 touch 7, flat-footed 13 touch 4, flat-footed', 12),
  ('monster-manual', 'other', 'Int —, Wis 1, Cha 1 Int —, Wis 1, Cha 1 Int —, Wis 1, Cha', 1),
  ('monster-manual', 'other', 'Challenge Rating: 3 5', 7),
  ('monster-manual', 'other', 'touch –1, flat-footed', 11),
  ('monster-manual', 'other', 'Int —, Wis 1, Cha', 1),
  ('monster-manual', 'other', 'Challenge Rating:', 10),
  ('monster-manual', 'other', 'the ankheg does not An aranea weighs about', 150);
