-- ============================================================================
-- POBLACIÓN COMPLETA DE LAS 11 CLASES BASE DE D&D 3.5
-- ============================================================================
-- Fecha: 2025-11-27
-- Descripción: Inserta las 11 clases base con información bilingüe (en/es)
-- Orden: Barbarian, Bard, Cleric, Druid, Fighter, Monk, Paladin, Ranger,
--        Rogue, Sorcerer, Wizard
-- ============================================================================

-- NOTA: Este archivo asume que ya se ejecutó 20251127_class_tables.sql

-- ============================================================================
-- 1. BARBARIAN (BÁRBARO) - YA COMPLETADO EN populate_barbarian.sql
-- ============================================================================
-- Ver archivo populate_barbarian.sql para detalles completos

-- ============================================================================
-- 2. BARD (BARDO)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'bard', 'Bardo', 'Bard', 'Bardo', 6, 6, 6, 6, 24,
  'average', 'medio', 'poor', 'pobre', 'good', 'bueno', 'good', 'bueno',
  'Charisma', 'Carisma',
  'Any nonlawful', 'Cualquiera no legal',
  'It is said that music has a special magic, and the bard proves that saying true. Wandering across the land, gathering lore, telling stories, working magic with his music, and living on the gratitude of his audience—such is the life of a bard.',
  'Se dice que la música tiene una magia especial, y el bardo demuestra que ese dicho es cierto. Vagando por la tierra, reuniendo conocimientos, contando historias, trabajando magia con su música y viviendo de la gratitud de su audiencia, así es la vida de un bardo.',
  'Versatile performer and spellcaster, inspires allies with bardic music',
  'Artista versátil y lanzador de conjuros, inspira aliados con música bárdica',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Appraise', 'Balance', 'Bluff', 'Climb', 'Concentration', 'Craft', 'Decipher Script', 'Diplomacy', 'Disguise', 'Escape Artist', 'Gather Information', 'Hide', 'Jump', 'Knowledge (all skills, taken individually)', 'Listen', 'Move Silently', 'Perform', 'Profession', 'Sense Motive', 'Sleight of Hand', 'Speak Language', 'Spellcraft', 'Swim', 'Tumble', 'Use Magic Device'],
  ARRAY['Tasar', 'Equilibrio', 'Engañar', 'Trepar', 'Concentración', 'Artesanía', 'Descifrar escritura', 'Diplomacia', 'Disfrazarse', 'Escapismo', 'Reunir información', 'Esconderse', 'Saltar', 'Conocimiento (todas las habilidades, tomadas individualmente)', 'Escuchar', 'Moverse sigilosamente', 'Actuar', 'Profesión', 'Sentir motivación', 'Juego de manos', 'Hablar idioma', 'Conjuros', 'Nadar', 'Voltereta', 'Usar objeto mágico'],
  'All simple weapons, plus longsword, rapier, sap, short sword, shortbow, and whip',
  'Todas las armas simples, más espada larga, estoque, cachiporra, espada corta, arco corto y látigo',
  'Light armor and shields (except tower shields)',
  'Armadura ligera y escudos (excepto escudos torre)'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 3. CLERIC (CLÉRIGO)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'cleric', 'Clérigo', 'Cleric', 'Clérigo', 8, 8, 2, 2, 8,
  'average', 'medio', 'good', 'bueno', 'poor', 'pobre', 'good', 'bueno',
  'Wisdom', 'Sabiduría',
  'Any', 'Cualquiera',
  'The handiwork of the gods is everywhere—in places of natural beauty, in mighty crusades, in soaring temples, and in the hearts of worshipers. The gods work mostly through intermediaries—their clerics. Good clerics heal, protect, and avenge. Evil clerics pillage, destroy, and sabotage.',
  'La obra de los dioses está en todas partes: en lugares de belleza natural, en poderosas cruzadas, en templos elevados y en los corazones de los adoradores. Los dioses trabajan principalmente a través de intermediarios: sus clérigos. Los clérigos buenos curan, protegen y vengan. Los clérigos malvados saquean, destruyen y sabotean.',
  'Divine spellcaster, channel of godly power, can turn undead',
  'Lanzador de conjuros divinos, canal del poder divino, puede repeler no-muertos',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Concentration', 'Craft', 'Diplomacy', 'Heal', 'Knowledge (arcana)', 'Knowledge (history)', 'Knowledge (religion)', 'Knowledge (the planes)', 'Profession', 'Spellcraft'],
  ARRAY['Concentración', 'Artesanía', 'Diplomacia', 'Sanar', 'Conocimiento (arcano)', 'Conocimiento (historia)', 'Conocimiento (religión)', 'Conocimiento (los planos)', 'Profesión', 'Conjuros'],
  'All simple weapons',
  'Todas las armas simples',
  'All armor and shields (except tower shields)',
  'Todas las armaduras y escudos (excepto escudos torre)'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 4. DRUID (DRUIDA)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'druid', 'Druida', 'Druid', 'Druida', 8, 8, 4, 4, 16,
  'average', 'medio', 'good', 'bueno', 'poor', 'pobre', 'good', 'bueno',
  'Wisdom', 'Sabiduría',
  'Any neutral', 'Cualquiera neutral',
  'The fury of a storm, the gentle strength of the morning sun, the cunning of the fox, the power of the bear—all these and more are at the druid''s command. The druid gains her power not by ruling nature but by being at one with it.',
  'La furia de una tormenta, la fuerza gentil del sol matutino, la astucia del zorro, el poder del oso: todo esto y más está al mando del druida. El druida obtiene su poder no gobernando la naturaleza sino siendo uno con ella.',
  'Divine spellcaster of nature, can wild shape into animals',
  'Lanzador de conjuros divinos de la naturaleza, puede transformarse en animales',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Concentration', 'Craft', 'Diplomacy', 'Handle Animal', 'Heal', 'Knowledge (nature)', 'Listen', 'Profession', 'Ride', 'Spellcraft', 'Spot', 'Survival', 'Swim'],
  ARRAY['Concentración', 'Artesanía', 'Diplomacia', 'Trato con animales', 'Sanar', 'Conocimiento (naturaleza)', 'Escuchar', 'Profesión', 'Montar', 'Conjuros', 'Avistar', 'Supervivencia', 'Nadar'],
  'Club, dagger, dart, quarterstaff, scimitar, sickle, shortspear, sling, and spear',
  'Garrote, daga, dardo, bastón, cimitarra, hoz, lanza corta, honda y lanza',
  'Light and medium armor, and shields (druids will not wear armor or use shields made of metal)',
  'Armadura ligera y media, y escudos (los druidas no usarán armadura ni escudos hechos de metal)'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 5. FIGHTER (GUERRERO)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'fighter', 'Guerrero', 'Fighter', 'Guerrero', 10, 10, 2, 2, 8,
  'good', 'bueno', 'good', 'bueno', 'poor', 'pobre', 'poor', 'pobre',
  'Strength', 'Fuerza',
  'Any', 'Cualquiera',
  'The fighter excels at combat—defeating his enemies, controlling the flow of battle, and surviving such sorties himself. While his specific weapons and methods grant him a wide variety of tactics, his expertise with weapons and armor is the foundation of his success.',
  'El guerrero sobresale en combate: derrotando a sus enemigos, controlando el flujo de la batalla y sobreviviendo a tales salidas él mismo. Si bien sus armas y métodos específicos le otorgan una amplia variedad de tácticas, su experiencia con armas y armaduras es la base de su éxito.',
  'Master of weapons and armor, excels at combat with bonus feats',
  'Maestro de armas y armaduras, sobresale en combate con dotes adicionales',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Climb', 'Craft', 'Handle Animal', 'Intimidate', 'Jump', 'Ride', 'Swim'],
  ARRAY['Trepar', 'Artesanía', 'Trato con animales', 'Intimidar', 'Saltar', 'Montar', 'Nadar'],
  'All simple and martial weapons',
  'Todas las armas simples y marciales',
  'All armor and shields (including tower shields)',
  'Todas las armaduras y escudos (incluyendo escudos torre)'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 6. MONK (MONJE)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'monk', 'Monje', 'Monk', 'Monje', 8, 8, 4, 4, 16,
  'average', 'medio', 'good', 'bueno', 'good', 'bueno', 'good', 'bueno',
  'Wisdom', 'Sabiduría',
  'Any lawful', 'Cualquiera legal',
  'Dotted across the landscape are monasteries—small, walled cloisters inhabited by monks who pursue personal perfection through action as well as contemplation. They train themselves to be versatile warriors skilled at fighting without weapons or armor.',
  'Dispersos por el paisaje hay monasterios: pequeños claustros amurallados habitados por monjes que buscan la perfección personal a través de la acción y la contemplación. Se entrenan para ser guerreros versátiles hábiles en luchar sin armas ni armadura.',
  'Martial artist with supernatural abilities, fights unarmed',
  'Artista marcial con habilidades sobrenaturales, lucha desarmado',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Balance', 'Climb', 'Concentration', 'Craft', 'Diplomacy', 'Escape Artist', 'Hide', 'Jump', 'Knowledge (arcana)', 'Knowledge (religion)', 'Listen', 'Move Silently', 'Perform', 'Profession', 'Sense Motive', 'Spot', 'Swim', 'Tumble'],
  ARRAY['Equilibrio', 'Trepar', 'Concentración', 'Artesanía', 'Diplomacia', 'Escapismo', 'Esconderse', 'Saltar', 'Conocimiento (arcano)', 'Conocimiento (religión)', 'Escuchar', 'Moverse sigilosamente', 'Actuar', 'Profesión', 'Sentir motivación', 'Avistar', 'Nadar', 'Voltereta'],
  'Club, crossbow (light or heavy), dagger, handaxe, javelin, kama, nunchaku, quarterstaff, sai, shuriken, siangham, and sling',
  'Garrote, ballesta (ligera o pesada), daga, hacha de mano, jabalina, kama, nunchaku, bastón, sai, shuriken, siangham y honda',
  'None (many monk abilities require unarmored movement)',
  'Ninguna (muchas habilidades de monje requieren movimiento sin armadura)'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 7. PALADIN (PALADÍN)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'paladin', 'Paladín', 'Paladin', 'Paladín', 10, 10, 2, 2, 8,
  'good', 'bueno', 'good', 'bueno', 'poor', 'pobre', 'poor', 'pobre',
  'Charisma', 'Carisma',
  'Lawful good only', 'Solo legal bueno',
  'The compassion to pursue good, the will to uphold law, and the power to defeat evil—these are the three weapons of the paladin. Few have the purity and devotion that it takes to walk the paladin''s path, but those few are rewarded with the power to protect, to heal, and to smite.',
  'La compasión para perseguir el bien, la voluntad para defender la ley y el poder para derrotar el mal: estas son las tres armas del paladín. Pocos tienen la pureza y devoción que se necesita para caminar el sendero del paladín, pero esos pocos son recompensados con el poder para proteger, curar y castigar.',
  'Holy warrior with divine powers, champion of good and law',
  'Guerrero sagrado con poderes divinos, campeón del bien y la ley',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Concentration', 'Craft', 'Diplomacy', 'Handle Animal', 'Heal', 'Knowledge (nobility and royalty)', 'Knowledge (religion)', 'Profession', 'Ride', 'Sense Motive'],
  ARRAY['Concentración', 'Artesanía', 'Diplomacia', 'Trato con animales', 'Sanar', 'Conocimiento (nobleza y realeza)', 'Conocimiento (religión)', 'Profesión', 'Montar', 'Sentir motivación'],
  'All simple and martial weapons',
  'Todas las armas simples y marciales',
  'All armor and shields (except tower shields)',
  'Todas las armaduras y escudos (excepto escudos torre)'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 8. RANGER (MONTARAZ)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'ranger', 'Montaraz', 'Ranger', 'Montaraz', 8, 8, 6, 6, 24,
  'good', 'bueno', 'good', 'bueno', 'good', 'bueno', 'poor', 'pobre',
  'Dexterity', 'Destreza',
  'Any', 'Cualquiera',
  'The forests and hills are home to fierce and cunning creatures, such as bloodthirsty owlbears and malicious displacer beasts. But more cunning and powerful than these monsters is the ranger, a skilled hunter and stalker. He knows the woods as if they were his home, which they are.',
  'Los bosques y colinas son el hogar de criaturas feroces y astutas, como osos búho sedientos de sangre y bestias desplazadoras maliciosas. Pero más astuto y poderoso que estos monstruos es el montaraz, un cazador y acechador hábil. Conoce los bosques como si fueran su hogar, que lo son.',
  'Skilled tracker and hunter, favored enemy specialist',
  'Rastreador y cazador hábil, especialista en enemigo predilecto',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Climb', 'Concentration', 'Craft', 'Handle Animal', 'Heal', 'Hide', 'Jump', 'Knowledge (dungeoneering)', 'Knowledge (geography)', 'Knowledge (nature)', 'Listen', 'Move Silently', 'Profession', 'Ride', 'Search', 'Spot', 'Survival', 'Swim', 'Use Rope'],
  ARRAY['Trepar', 'Concentración', 'Artesanía', 'Trato con animales', 'Sanar', 'Esconderse', 'Saltar', 'Conocimiento (mazmorras)', 'Conocimiento (geografía)', 'Conocimiento (naturaleza)', 'Escuchar', 'Moverse sigilosamente', 'Profesión', 'Montar', 'Buscar', 'Avistar', 'Supervivencia', 'Nadar', 'Usar cuerdas'],
  'All simple and martial weapons',
  'Todas las armas simples y marciales',
  'Light armor and shields (except tower shields)',
  'Armadura ligera y escudos (excepto escudos torre)'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 9. ROGUE (PÍCARO)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'rogue', 'Pícaro', 'Rogue', 'Pícaro', 6, 6, 8, 8, 32,
  'average', 'medio', 'poor', 'pobre', 'good', 'bueno', 'poor', 'pobre',
  'Dexterity', 'Destreza',
  'Any', 'Cualquiera',
  'Rogues have little in common with each other. Some are stealthy thieves. Others are silver-tongued tricksters. Still others are scouts, infiltrators, spies, diplomats, or thugs. What they share is versatility, adaptability, and resourcefulness.',
  'Los pícaros tienen poco en común entre sí. Algunos son ladrones sigilosos. Otros son embaucadores de lengua de plata. Otros son exploradores, infiltradores, espías, diplomáticos o matones. Lo que comparten es versatilidad, adaptabilidad e ingenio.',
  'Skilled and versatile, master of stealth and sneak attack',
  'Hábil y versátil, maestro del sigilo y ataque furtivo',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Appraise', 'Balance', 'Bluff', 'Climb', 'Craft', 'Decipher Script', 'Diplomacy', 'Disable Device', 'Disguise', 'Escape Artist', 'Forgery', 'Gather Information', 'Hide', 'Intimidate', 'Jump', 'Knowledge (local)', 'Listen', 'Move Silently', 'Open Lock', 'Perform', 'Profession', 'Search', 'Sense Motive', 'Sleight of Hand', 'Spot', 'Swim', 'Tumble', 'Use Magic Device', 'Use Rope'],
  ARRAY['Tasar', 'Equilibrio', 'Engañar', 'Trepar', 'Artesanía', 'Descifrar escritura', 'Diplomacia', 'Inutilizar mecanismo', 'Disfrazarse', 'Escapismo', 'Falsificar', 'Reunir información', 'Esconderse', 'Intimidar', 'Saltar', 'Conocimiento (local)', 'Escuchar', 'Moverse sigilosamente', 'Abrir cerraduras', 'Actuar', 'Profesión', 'Buscar', 'Sentir motivación', 'Juego de manos', 'Avistar', 'Nadar', 'Voltereta', 'Usar objeto mágico', 'Usar cuerdas'],
  'All simple weapons, plus hand crossbow, rapier, sap, shortbow, and short sword',
  'Todas las armas simples, más ballesta de mano, estoque, cachiporra, arco corto y espada corta',
  'Light armor',
  'Armadura ligera'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 10. SORCERER (HECHICERO)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'sorcerer', 'Hechicero', 'Sorcerer', 'Hechicero', 4, 4, 2, 2, 8,
  'poor', 'pobre', 'poor', 'pobre', 'poor', 'pobre', 'good', 'bueno',
  'Charisma', 'Carisma',
  'Any', 'Cualquiera',
  'Sorcerers create magic the way a poet creates poems, with inborn talent honed by practice. They have no books, no mentors, no theories—just raw power that they direct at will. Some sorcerers claim that the blood of dragons courses through their veins.',
  'Los hechiceros crean magia de la manera en que un poeta crea poemas, con talento innato perfeccionado por la práctica. No tienen libros, ni mentores, ni teorías, solo poder puro que dirigen a voluntad. Algunos hechiceros afirman que la sangre de dragones corre por sus venas.',
  'Innate arcane spellcaster, casts spontaneously without preparation',
  'Lanzador de conjuros arcanos innato, lanza espontáneamente sin preparación',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Bluff', 'Concentration', 'Craft', 'Knowledge (arcana)', 'Profession', 'Spellcraft'],
  ARRAY['Engañar', 'Concentración', 'Artesanía', 'Conocimiento (arcano)', 'Profesión', 'Conjuros'],
  'All simple weapons',
  'Todas las armas simples',
  'None',
  'Ninguna'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- 11. WIZARD (MAGO)
-- ============================================================================

INSERT INTO classes (
  slug, titulo, name_en, name_es, hit_die, dg, 
  skill_points_per_level, skill_points_per_level_base, skill_points_first_level_base,
  bab_progression, bab, fort_save, fort, ref_save, ref, will_save, will,
  primary_ability_en, primary_ability_es,
  alignment_restriction_en, alignment_restriction_es,
  description_en, description_es,
  summary_en, summary_es,
  source_en, source_es,
  class_skills_en, class_skills_es,
  weapon_proficiencies_en, weapon_proficiencies_es,
  armor_proficiencies_en, armor_proficiencies_es
) VALUES (
  'wizard', 'Mago', 'Wizard', 'Mago', 4, 4, 2, 2, 8,
  'poor', 'pobre', 'poor', 'pobre', 'poor', 'pobre', 'good', 'bueno',
  'Intelligence', 'Inteligencia',
  'Any', 'Cualquiera',
  'A few unintelligible words and fleeting gestures carry more power than a battleaxe, when they are the words and gestures of a wizard. These simple acts make magic seem easy, but they only hint at the time the wizard must spend poring over her spellbook preparing each spell for casting.',
  'Unas pocas palabras ininteligibles y gestos fugaces llevan más poder que un hacha de batalla, cuando son las palabras y gestos de un mago. Estos actos simples hacen que la magia parezca fácil, pero solo insinúan el tiempo que el mago debe pasar estudiando su libro de conjuros preparando cada hechizo para lanzar.',
  'Master of arcane magic through study and preparation',
  'Maestro de la magia arcana a través del estudio y la preparación',
  'Player''s Handbook v3.5', 'Manual del Jugador v3.5',
  ARRAY['Concentration', 'Craft', 'Decipher Script', 'Knowledge (all skills, taken individually)', 'Profession', 'Spellcraft'],
  ARRAY['Concentración', 'Artesanía', 'Descifrar escritura', 'Conocimiento (todas las habilidades, tomadas individualmente)', 'Profesión', 'Conjuros'],
  'Club, dagger, heavy crossbow, light crossbow, and quarterstaff',
  'Garrote, daga, ballesta pesada, ballesta ligera y bastón',
  'None',
  'Ninguna'
) ON CONFLICT (slug) DO UPDATE SET
  titulo = EXCLUDED.titulo,
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  hit_die = EXCLUDED.hit_die,
  dg = EXCLUDED.dg,
  skill_points_per_level = EXCLUDED.skill_points_per_level,
  skill_points_per_level_base = EXCLUDED.skill_points_per_level_base,
  skill_points_first_level_base = EXCLUDED.skill_points_first_level_base,
  bab_progression = EXCLUDED.bab_progression,
  bab = EXCLUDED.bab,
  fort_save = EXCLUDED.fort_save,
  fort = EXCLUDED.fort,
  ref_save = EXCLUDED.ref_save,
  ref = EXCLUDED.ref,
  will_save = EXCLUDED.will_save,
  will = EXCLUDED.will,
  primary_ability_en = EXCLUDED.primary_ability_en,
  primary_ability_es = EXCLUDED.primary_ability_es,
  alignment_restriction_en = EXCLUDED.alignment_restriction_en,
  alignment_restriction_es = EXCLUDED.alignment_restriction_es,
  description_en = EXCLUDED.description_en,
  description_es = EXCLUDED.description_es,
  summary_en = EXCLUDED.summary_en,
  summary_es = EXCLUDED.summary_es,
  source_en = EXCLUDED.source_en,
  source_es = EXCLUDED.source_es,
  class_skills_en = EXCLUDED.class_skills_en,
  class_skills_es = EXCLUDED.class_skills_es,
  weapon_proficiencies_en = EXCLUDED.weapon_proficiencies_en,
  weapon_proficiencies_es = EXCLUDED.weapon_proficiencies_es,
  armor_proficiencies_en = EXCLUDED.armor_proficiencies_en,
  armor_proficiencies_es = EXCLUDED.armor_proficiencies_es;

-- ============================================================================
-- RESUMEN
-- ============================================================================
-- Este archivo inserta la información básica de las 11 clases base.
-- Para información completa de progresión, características y starting packages:
-- - Ver populate_barbarian.sql para el ejemplo completo del Bárbaro
-- - Las demás clases necesitarán archivos similares con sus detalles específicos
-- ============================================================================

COMMENT ON TABLE classes IS 'Contiene las 11 clases base de D&D 3.5 con información bilingüe';
